// API SURFACE SNAPSHOT — @partylayer/registry-client
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class RegistryClient { private baseUrl; private channel; private publicKeys; private cacheTtl; private staleTtl; private enableCache; private fetchFn; private fetchTimeout; private storage?; private memoryCache; private currentStatus; constructor(options?: RegistryClientOptions); private getRegistryUrl; private getSignatureUrl; private importPublicKey; private verifySignature; private verifyRegistrySignature; private fetchFromNetwork; getRegistry(): Promise<WalletRegistryV1>; private refreshRegistry; private updateStatus; getStatus(): RegistryStatus | null; private saveToStorage; private loadFromStorage; getWallets(): Promise<WalletInfo[]>; getWallet(walletId: string): Promise<WalletInfo>; getWalletEntry(walletId: string): Promise<RegistryWalletEntry>; clearCache(): void; isCacheValid(): boolean; }
declare const REGISTRY_SCHEMA_VERSION = "1.0.0";
declare function registryEntryToMetadata(entry: RegistryWalletEntry): WalletInfo;
declare function registryEntryToWalletInfo(entry: RegistryWalletEntry, channel: RegistryChannel): WalletInfo;
declare function validateRegistry(registry: unknown): registry is WalletRegistryV1;
declare function validateWalletEntry(entry: unknown): entry is RegistryWalletEntry;
export { Cip0103StatusForDetection, Cip0103Support, ProviderDetection, ProviderMatcher, WalletInfo, deriveGenericWalletName, findMatchingWallet, findMatchingWalletInfo, isCip0103Native, matchesProviderDetection } from '@partylayer/core';
export { type CachedRegistry, type LastFetchAttempt, REGISTRY_SCHEMA_VERSION, type RegistryChannel, RegistryClient, type RegistryClientOptions, type RegistryMetadata, type RegistrySignature, type RegistryStatus, type RegistryWalletEntry, type WalletRegistryV1, registryEntryToMetadata, registryEntryToWalletInfo, validateRegistry, validateWalletEntry };
import { NetworkId, AdapterTransport, ProviderDetection, Cip0103Support, WalletInfo, PartyLayerError } from '@partylayer/core';
interface CachedRegistry { registry: WalletRegistryV1; verified: boolean; fetchedAt: number; etag?: string; sequence: number; }
interface LastFetchAttempt { fetchedAt: number; errorCode?: string; }
interface RegistryClientOptions { registryUrl?: string; channel?: RegistryChannel; registryPublicKeys?: string[]; cacheTtl?: number; staleTtl?: number; enableCache?: boolean; fetch?: typeof fetch; fetchTimeout?: number; storage?: { get(key: string): Promise<string | null>; set(key: string, value: string): Promise<void>; remove(key: string): Promise<void>; }; }
interface RegistryMetadata { registryVersion: string; schemaVersion: string; publishedAt: string; channel: RegistryChannel; sequence: number; publisher?: string; }
interface RegistrySignature { algorithm: 'ed25519'; signature: string; keyFingerprint: string; signedAt: string; }
interface RegistryStatus { source: 'network' | 'cache'; verified: boolean; channel: RegistryChannel; sequence: number; stale: boolean; fetchedAt: number; etag?: string; error?: PartyLayerError; }
interface RegistryWalletEntry { id: string; name: string; description?: string; homepage?: string; icon?: string; supportedNetworks: NetworkId[]; capabilities: { signMessage: boolean; signTransaction: boolean; submitTransaction: boolean; transactionStatus: boolean; switchNetwork: boolean; multiParty: boolean; mobileConnect?: boolean; remoteSigner?: boolean; events?: boolean; }; adapter: { type: string; transport?: AdapterTransport; config?: Record<string, unknown>; }; installation?: { windowProperty?: string; scriptTag?: string; extensionId?: string; deeplink?: string; oauth?: boolean; }; sdkVersion?: string; version?: string; originAllowlist?: string[]; beta?: boolean; providerDetection?: ProviderDetection; cip0103?: Cip0103Support; }
interface WalletRegistryV1 { metadata: RegistryMetadata; wallets: RegistryWalletEntry[]; }
type RegistryChannel = 'stable' | 'beta';
