// API SURFACE SNAPSHOT — @partylayer/adapter-cantor8
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class Cantor8Adapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Cantor8"; private vendorModule; private vendorConfig; private transport; constructor(config?: Cantor8AdapterConfig); getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, opts?: { timeoutMs?: number; partyId?: _partylayer_core.PartyId; }): Promise<AdapterConnectResult>; disconnect(_ctx: AdapterContext, _session: _partylayer_core.Session): Promise<void>; restore(_ctx: AdapterContext, persisted: _partylayer_core.PersistedSession): Promise<_partylayer_core.Session | null>; signMessage(ctx: AdapterContext, session: _partylayer_core.Session, params: SignMessageParams): Promise<_partylayer_core.SignedMessage>; signTransaction(ctx: AdapterContext, session: _partylayer_core.Session, params: SignTransactionParams): Promise<_partylayer_core.SignedTransaction>; private generateState; }
export { Cantor8Adapter, type Cantor8AdapterConfig };
import * as _partylayer_core from '@partylayer/core';
import { ConnectRequest, ConnectResponse, SignRequest, SignResponse, JobStatus, WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, AdapterConnectResult, SignMessageParams, SignTransactionParams } from '@partylayer/core';
interface Cantor8AdapterConfig { vendorModule?: Cantor8VendorModule; vendorConfig?: Cantor8VendorConfig; useMockTransport?: boolean; }
interface Cantor8VendorConfig { deepLinkScheme?: string; universalLinkBase?: string; connectEndpoint?: string; signEndpoint?: string; statusEndpoint?: string; redirectUri?: string; }
interface Cantor8VendorModule { createConnectUrl(request: ConnectRequest, config: Cantor8VendorConfig): string; parseConnectCallback(callbackData: unknown, expectedState: string): ConnectResponse; createSignUrl(request: SignRequest, config: Cantor8VendorConfig): string; parseSignCallback(callbackData: unknown, expectedState: string): SignResponse; pollJobStatus?(jobId: string, statusUrl: string, timeoutMs: number): Promise<JobStatus>; }
