// API SURFACE SNAPSHOT — @partylayer/core
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
/**
 * Core types for PartyLayer SDK
 *
 * References:
 * - Wallet Integration Guide: https://docs.digitalasset.com/integrate/devnet/index.html
 * - Signing transactions from dApps: https://docs.digitalasset.com/integrate/devnet/signing-transactions-from-dapps/index.html
 * - OpenRPC dApp API spec: https://github.com/hyperledger-labs/splice-wallet-kernel/blob/main/api-specs/openrpc-dapp-api.json
 */
/**
 * Branded string types for type safety
 */
type WalletId = string & {
  readonly __brand: 'WalletId';
};
type PartyId = string & {
  readonly __brand: 'PartyId';
};
type SessionId = string & {
  readonly __brand: 'SessionId';
};
type TransactionHash = string & {
  readonly __brand: 'TransactionHash';
};
type Signature = string & {
  readonly __brand: 'Signature';
};
/**
 * Network identifier
 * Standard networks: "devnet" | "testnet" | "mainnet"
 * Custom networks allowed as string
 */
type NetworkId = 'devnet' | 'testnet' | 'mainnet' | (string & Record<never, never>);
/**
 * Capability keys that wallets can support
 * Based on OpenRPC dApp API capabilities
 */
type CapabilityKey =
  | 'connect'
  | 'disconnect'
  | 'restore'
  | 'signMessage'
  | 'signTransaction'
  | 'submitTransaction'
  | 'ledgerApi'
  | 'events'
  | 'deeplink'
  | 'popup'
  | 'injected'
  | 'remoteSigner';
/**
 * Wallet installation hints for detection
 */
interface InstallHints {
  /** Window property name (e.g., "consoleWallet") */
  injectedKey?: string;
  /** Browser extension ID */
  extensionId?: string;
  /** Deep link scheme (e.g., "loop://") */
  deepLinkScheme?: string;
  /** Script tag identifier */
  scriptTag?: string;
}
/**
 * Wallet adapter metadata
 */
interface AdapterMetadata {
  /** NPM package name */
  packageName: string;
  /** Version range (semver) */
  versionRange: string;
}
/**
 * Provider matcher: a single rule used by `ProviderDetection.matchers`.
 *
 * Three match modes are defined; OR-combined inside a `ProviderDetection`.
 * Exact and prefix work on string fields directly; domain interprets the
 * field as a URL and tests its hostname against the registrable domain
 * (with subdomain support).
 */
type ProviderMatcher =
  | {
      field: 'kernel.url' | 'kernel.userUrl';
      match: 'domain';
      /** Hostname or registrable domain. Subdomains are accepted. */
      value: string;
    }
  | {
      field: 'kernel.id' | 'kernel.url' | 'kernel.userUrl' | 'kernel.clientType' | 'provider.id';
      match: 'exact';
      /** One or more exact values; ANY match returns true. */
      values: string[];
    }
  | {
      field: 'kernel.id' | 'kernel.url' | 'kernel.userUrl';
      match: 'prefix';
      value: string;
    };
/**
 * Standards-first runtime detection of a CIP-0103 wallet.
 *
 * The registry stores these rules so that any current or future wallet
 * implementing `window.canton` can be identified without code changes —
 * a registry JSON update is enough.
 */
interface ProviderDetection {
  /** Transport mechanism. Currently only 'window.canton' is supported. */
  transport: 'window.canton';
  /** OR-list of matchers. Provider matches if ANY matcher returns true. */
  matchers: ProviderMatcher[];
}
/**
 * Canonical CIP-0103 support marker.
 *
 * When `native: true`, the wallet is treated as a first-class CIP-0103
 * provider in the picker — it always appears in the "CIP-0103 NATIVE"
 * section regardless of install state, with a per-wallet readiness
 * indicator that reflects whether the wallet's `providerDetection` rules
 * matched the currently-injected `window.canton` provider.
 *
 * The field is optional; wallets that don't claim CIP-0103 support omit
 * it and continue to appear in the "AVAILABLE" section as before.
 */
interface Cip0103Support {
  /** True if this wallet has confirmed CIP-0103 dApp API support. */
  native: boolean;
  /** Public evidence link (npm package, blog post, official statement). */
  evidence?: string;
  /** ISO date when CIP-0103 support was confirmed (informational). */
  since?: string;
}
/**
 * How the SDK obtains a wallet's provider for a registry entry.
 *
 * - `'injected'`          — `window.canton.*` scanning (the implicit default
 *                           behavior when `transport` is omitted).
 * - `'announce'`          — CIP-0103 `canton:announceProvider` discovery.
 * - `'discovery-adapter'` — the provider comes from an app-supplied
 *                           `OfficialProviderAdapter` (the official
 *                           `@canton-network/core-wallet-discovery`
 *                           `ProviderAdapter` shape), bridged generically by
 *                           the SDK. For popup/remote wallets that neither
 *                           inject `window.canton` nor announce. No
 *                           wallet-specific adapter package is involved.
 *
 * Additive + optional: older registries omit it and keep today's behavior.
 */
type AdapterTransport = 'injected' | 'announce' | 'discovery-adapter';
/**
 * Wallet information from registry
 */
interface WalletInfo {
  /** Wallet identifier */
  walletId: WalletId;
  /** Display name */
  name: string;
  /** Website URL */
  website: string;
  /** Icon URLs (different sizes) */
  icons: {
    sm?: string;
    md?: string;
    lg?: string;
  };
  /** Category (e.g., "browser", "mobile", "hardware") */
  category?: string;
  /** Supported capabilities */
  capabilities: CapabilityKey[];
  /** Installation detection hints */
  installHints?: InstallHints;
  /** Adapter package information */
  adapter: AdapterMetadata;
  /** Documentation URLs */
  docs: string[];
  /** Minimum SDK version required */
  minSdkVersion?: string;
  /** Supported networks */
  networks: NetworkId[];
  /** Registry channel */
  channel: 'stable' | 'beta';
  /** Additional metadata (e.g., originAllowlist) */
  metadata?: Record<string, string>;
  /**
   * Optional CIP-0103 runtime detection rules. When present, the picker can
   * decide whether this wallet is the currently-injected `window.canton`
   * provider and route it into the "CIP-0103 Native" section without any
   * hardcoded wallet IDs. Wallets that aren't CIP-0103-injected (e.g. Bron,
   * Cantor8 deeplink) leave this unset.
   */
  providerDetection?: ProviderDetection;
  /**
   * Canonical CIP-0103 support marker. When set with `native: true`, the
   * picker always lists the wallet in the "CIP-0103 NATIVE" section
   * regardless of install state.
   */
  cip0103?: Cip0103Support;
}
/**
 * Returns true if the wallet has been canonically marked as CIP-0103
 * native via its registry entry. The check is structural so it works on
 * both raw `RegistryWalletEntry` shapes and converted `WalletInfo`.
 */
declare function isCip0103Native(entry: { cip0103?: Cip0103Support }): boolean;
/**
 * Session information
 * Sessions are origin-bound and encrypted in storage
 */
interface Session {
  /** Unique session ID */
  sessionId: SessionId;
  /** Wallet identifier */
  walletId: WalletId;
  /** Connected party ID */
  partyId: PartyId;
  /** Current network */
  network: NetworkId;
  /** Session creation timestamp */
  createdAt: number;
  /** Session expiration timestamp (if applicable) */
  expiresAt?: number;
  /** Origin of the dApp that created the session */
  origin: string;
  /** Capabilities available in this session */
  capabilitiesSnapshot: CapabilityKey[];
  /** Additional metadata (encrypted in storage) */
  metadata?: Record<string, string>;
  /**
   * Set when the wallet's reported network differs from the dApp's configured
   * network (CAIP-2 normalized). Absent when the networks match or no confident
   * mismatch was detected. See `networkEnforcement` for blocking behavior.
   */
  networkMismatch?: {
    expected: string;
    actual: string;
  };
}
/**
 * Persisted session (for restoration)
 */
interface PersistedSession extends Session {
  /** Encrypted session data */
  encrypted: string;
}
/**
 * Signed message result
 */
interface SignedMessage {
  /** Signature */
  signature: Signature;
  /** Party ID that signed */
  partyId: PartyId;
  /** Original message */
  message: string;
  /** Nonce used (if provided) */
  nonce?: string;
  /** Domain used (if provided) */
  domain?: string;
}
/**
 * Signed transaction result
 */
interface SignedTransaction {
  /** Signed transaction data */
  signedTx: unknown;
  /** Transaction hash */
  transactionHash: TransactionHash;
  /** Party ID that signed */
  partyId: PartyId;
}
/**
 * Transaction receipt
 */
interface TxReceipt {
  /** Transaction hash */
  transactionHash: TransactionHash;
  /** Submission timestamp */
  submittedAt: number;
  /** Command ID (if available) */
  commandId?: string;
  /** Update ID (if available) */
  updateId?: string;
}
/**
 * Transaction status
 */
type TransactionStatus = 'pending' | 'submitted' | 'committed' | 'rejected' | 'failed';
/**
 * Transaction status update
 */
interface TxStatusUpdate {
  /** Session ID */
  sessionId: SessionId;
  /** Transaction ID */
  txId: TransactionHash;
  /** Current status */
  status: TransactionStatus;
  /** Raw transaction data (if available) */
  raw?: unknown;
  /** Timestamp */
  timestamp: number;
}
/**
 * Helper to create branded WalletId
 */
declare function toWalletId(id: string): WalletId;
/**
 * Helper to create branded PartyId
 */
declare function toPartyId(id: string): PartyId;
/**
 * Helper to create branded SessionId
 */
declare function toSessionId(id: string): SessionId;
/**
 * Helper to create branded TransactionHash
 */
declare function toTransactionHash(hash: string): TransactionHash;
/**
 * Helper to create branded Signature
 */
declare function toSignature(sig: string): Signature;

/**
 * Error taxonomy for PartyLayer SDK
 *
 * All errors extend PartyLayerError with stable error codes.
 * Error codes are string literals for telemetry and UI message mapping.
 *
 * References:
 * - Wallet Integration Guide: https://docs.digitalasset.com/integrate/devnet/index.html
 */
/**
 * Error code union - stable string literals for telemetry and UI
 */
type ErrorCode =
  | 'WALLET_NOT_FOUND'
  | 'WALLET_NOT_INSTALLED'
  | 'USER_REJECTED'
  | 'ORIGIN_NOT_ALLOWED'
  | 'SESSION_EXPIRED'
  | 'CAPABILITY_NOT_SUPPORTED'
  | 'TRANSPORT_ERROR'
  | 'REGISTRY_FETCH_FAILED'
  | 'REGISTRY_VERIFICATION_FAILED'
  | 'REGISTRY_SCHEMA_INVALID'
  | 'INTERNAL_ERROR'
  | 'NETWORK_MISMATCH'
  | 'TIMEOUT';
/**
 * Error mapping context
 */
interface ErrorMappingContext {
  /** Wallet ID (if applicable) */
  walletId?: string;
  /** Operation phase */
  phase:
    | 'connect'
    | 'restore'
    | 'signMessage'
    | 'signTransaction'
    | 'submitTransaction'
    | 'ledgerApi';
  /** Transport type */
  transport?: 'injected' | 'popup' | 'deeplink' | 'remote';
  /** Timeout in milliseconds (for timeout errors) */
  timeoutMs?: number;
  /** Additional context */
  details?: Record<string, unknown>;
}
/**
 * Base error class for all PartyLayer errors
 */
declare class PartyLayerError extends Error {
  readonly code: ErrorCode;
  readonly cause?: unknown;
  readonly details?: Record<string, unknown>;
  readonly isOperational: boolean;
  constructor(
    message: string,
    code: ErrorCode,
    options?: {
      cause?: unknown;
      details?: Record<string, unknown>;
      isOperational?: boolean;
    }
  );
  /**
   * Serialize error to JSON for telemetry/logging
   */
  toJSON(): Record<string, unknown>;
}
/**
 * Wallet not found error
 */
declare class WalletNotFoundError extends PartyLayerError {
  constructor(walletId: string);
}
/**
 * Wallet not installed error
 */
declare class WalletNotInstalledError extends PartyLayerError {
  constructor(walletId: string, reason?: string);
}
/**
 * User rejected error
 */
declare class UserRejectedError extends PartyLayerError {
  constructor(operation: string, details?: Record<string, unknown>);
}
/**
 * Origin not allowed error
 */
declare class OriginNotAllowedError extends PartyLayerError {
  constructor(origin: string, allowedOrigins?: string[]);
}
/**
 * Session expired error
 */
declare class SessionExpiredError extends PartyLayerError {
  constructor(sessionId: string);
}
/**
 * Network mismatch error — the connected wallet's effective network differs
 * from the dApp's configured network. Thrown to block wrong-network connects
 * (policy 'strict') and wrong-network transactions (policy 'guard' | 'strict').
 */
declare class NetworkMismatchError extends PartyLayerError {
  /** The dApp's configured (expected) network, CAIP-2 normalized. */
  readonly expected: string;
  /** The wallet's reported (actual) network, CAIP-2 normalized. */
  readonly actual: string;
  constructor(expected: string, actual: string);
}
/**
 * Capability not supported error
 */
declare class CapabilityNotSupportedError extends PartyLayerError {
  constructor(walletId: string, capability: string);
}
/**
 * Transport error
 */
declare class TransportError extends PartyLayerError {
  constructor(message: string, cause?: unknown, details?: Record<string, unknown>);
}
/**
 * Registry fetch failed error
 */
declare class RegistryFetchFailedError extends PartyLayerError {
  constructor(url: string, cause?: unknown);
}
/**
 * Registry verification failed error
 */
declare class RegistryVerificationFailedError extends PartyLayerError {
  constructor(reason: string, details?: Record<string, unknown>);
}
/**
 * Registry schema invalid error
 */
declare class RegistrySchemaInvalidError extends PartyLayerError {
  constructor(reason: string, details?: Record<string, unknown>);
}
/**
 * Internal error (non-operational)
 */
declare class InternalError extends PartyLayerError {
  constructor(message: string, cause?: unknown, details?: Record<string, unknown>);
}
/**
 * Timeout error
 */
declare class TimeoutError extends PartyLayerError {
  constructor(operation: string, timeoutMs: number);
}
/**
 * Map unknown errors to PartyLayerError
 *
 * This is the single error mapping strategy used by all adapters.
 * It normalizes errors from various sources (wallet SDKs, network, etc.)
 * into typed PartyLayerError instances.
 */
declare function mapUnknownErrorToPartyLayerError(
  err: unknown,
  context: ErrorMappingContext
): PartyLayerError;

/**
 * CIP-0103 dApp Standard — Canonical Type Definitions
 *
 * These types are the verbatim representation of the CIP-0103 specification.
 * They live in @partylayer/core so both @partylayer/provider and @partylayer/sdk
 * can reference them without circular dependencies.
 *
 * Reference: https://github.com/canton-foundation/cips/blob/main/cip-0103/cip-0103.md
 *
 * IMPORTANT: Do not add PartyLayer-specific fields or aliases.
 * These types represent the standard exactly.
 */
type CIP0103EventListener<T = unknown> = (...args: T[]) => void;
type CIP0103RequestParams = unknown[] | Record<string, unknown>;
interface CIP0103RequestPayload {
  method: string;
  params?: CIP0103RequestParams;
}
interface CIP0103Provider {
  request<T = unknown>(args: CIP0103RequestPayload): Promise<T>;
  on<T = unknown>(event: string, listener: CIP0103EventListener<T>): CIP0103Provider;
  emit<T = unknown>(event: string, ...args: T[]): boolean;
  removeListener<T = unknown>(
    event: string,
    listenerToRemove: CIP0103EventListener<T>
  ): CIP0103Provider;
}
interface CIP0103ConnectResult {
  isConnected: boolean;
  reason?: string;
  isNetworkConnected?: boolean;
  networkReason?: string;
  /** Async wallet extension: URL for user to complete connection */
  userUrl?: string;
}
interface CIP0103Network {
  /** CAIP-2 network identifier, e.g. "canton:da-mainnet" */
  networkId: string;
  /** JSON Ledger API endpoint (if available) */
  ledgerApi?: string;
  /** Access token for Ledger API (if available) */
  accessToken?: string;
}
type CIP0103AccountStatus = 'initializing' | 'allocated';
interface CIP0103Account {
  primary: boolean;
  partyId: string;
  status: CIP0103AccountStatus;
  hint: string;
  publicKey: string;
  namespace: string;
  /** CAIP-2 network identifier */
  networkId: string;
  signingProviderId: string;
}
type CIP0103ProviderType = 'browser' | 'desktop' | 'mobile' | 'remote';
interface CIP0103ProviderInfo {
  id: string;
  /** dApp API version */
  version: string;
  providerType: CIP0103ProviderType;
}
interface CIP0103StatusEvent {
  connection: CIP0103ConnectResult;
  provider: CIP0103ProviderInfo;
  network?: CIP0103Network;
  session?: {
    accessToken: string;
    userId: string;
  };
}
type CIP0103TxStatus = 'pending' | 'signed' | 'executed' | 'failed';
interface CIP0103TxPendingPayload {
  status: 'pending';
  commandId: string;
}
interface CIP0103TxSignedPayload {
  status: 'signed';
  commandId: string;
  payload: {
    signature: string;
    signedBy: string;
    party: string;
  };
}
interface CIP0103TxExecutedPayload {
  status: 'executed';
  commandId: string;
  payload: {
    updateId: string;
    completionOffset: number;
  };
}
interface CIP0103TxFailedPayload {
  status: 'failed';
  commandId: string;
}
type CIP0103TxChangedEvent =
  | CIP0103TxPendingPayload
  | CIP0103TxSignedPayload
  | CIP0103TxExecutedPayload
  | CIP0103TxFailedPayload;
interface CIP0103LedgerApiRequest {
  requestMethod: 'GET' | 'POST' | 'PUT' | 'DELETE';
  resource: string;
  body?: string;
}
interface CIP0103LedgerApiResponse {
  response: string;
}
interface CIP0103SignMessageRequest {
  message: string;
}
interface CIP0103ProviderRpcError {
  code: number;
  message: string;
  data?: unknown;
}
declare const CIP0103_METHODS: {
  readonly CONNECT: 'connect';
  readonly DISCONNECT: 'disconnect';
  readonly IS_CONNECTED: 'isConnected';
  readonly STATUS: 'status';
  readonly GET_ACTIVE_NETWORK: 'getActiveNetwork';
  readonly LIST_ACCOUNTS: 'listAccounts';
  readonly GET_PRIMARY_ACCOUNT: 'getPrimaryAccount';
  readonly SIGN_MESSAGE: 'signMessage';
  readonly PREPARE_EXECUTE: 'prepareExecute';
  readonly LEDGER_API: 'ledgerApi';
};
type CIP0103Method = (typeof CIP0103_METHODS)[keyof typeof CIP0103_METHODS];
/** All mandatory method names as an array (useful for conformance testing) */
declare const CIP0103_MANDATORY_METHODS: readonly CIP0103Method[];
declare const CIP0103_EVENTS: {
  readonly STATUS_CHANGED: 'statusChanged';
  readonly ACCOUNTS_CHANGED: 'accountsChanged';
  readonly TX_CHANGED: 'txChanged';
  /** Emitted when async connect completes */
  readonly CONNECTED: 'connected';
};
type CIP0103Event = (typeof CIP0103_EVENTS)[keyof typeof CIP0103_EVENTS];

/**
 * Wallet adapter interface contract
 *
 * All wallet adapters must implement this interface.
 * Adapters are responsible for:
 * - Detecting wallet installation
 * - Establishing connections
 * - Signing messages/transactions
 * - Emitting events
 *
 * References:
 * - OpenRPC dApp API spec: https://github.com/hyperledger-labs/splice-wallet-kernel/blob/main/api-specs/openrpc-dapp-api.json
 * - Wallet Integration Guide: https://docs.digitalasset.com/integrate/devnet/index.html
 */

/**
 * Adapter detection result
 */
interface AdapterDetectResult {
  /** Whether wallet is installed */
  installed: boolean;
  /** Reason if not installed */
  reason?: string;
}
/**
 * Adapter connection result
 */
interface AdapterConnectResult {
  /** Connected party ID */
  partyId: PartyId;
  /** Partial session data (SDK will complete it) */
  session: Partial<Session>;
  /** Capabilities available in this session */
  capabilities: CapabilityKey[];
}
/**
 * Sign message parameters
 */
interface SignMessageParams {
  /** Message to sign */
  message: string;
  /** Optional nonce */
  nonce?: string;
  /** Optional domain */
  domain?: string;
}
/**
 * Sign transaction parameters
 */
interface SignTransactionParams {
  /** Transaction to sign (type kept as unknown for wallet-specific formats) */
  tx: unknown;
}
/**
 * Submit transaction parameters
 */
interface SubmitTransactionParams {
  /** Signed transaction */
  signedTx: unknown;
}
/**
 * Ledger API proxy parameters (CIP-0103 ledgerApi method)
 */
interface LedgerApiParams {
  /** HTTP method for the JSON Ledger API */
  requestMethod: 'GET' | 'POST' | 'PUT' | 'DELETE';
  /** Resource path (e.g., "/v2/state/acs") */
  resource: string;
  /** Optional JSON body */
  body?: string;
}
/**
 * Ledger API proxy result
 */
interface LedgerApiResult {
  /** JSON response from the Ledger API */
  response: string;
}
/**
 * Logger interface
 */
interface LoggerAdapter {
  debug(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  error(message: string, error?: unknown, ...args: unknown[]): void;
}
/**
 * Telemetry interface
 *
 * Extended in 0.3.0 with optional metrics methods.
 * All new methods are optional to maintain backward compatibility.
 */
interface TelemetryAdapter {
  /** Track a named event with optional properties */
  track(event: string, properties?: Record<string, unknown>): void;
  /** Track an error occurrence */
  error(error: Error, properties?: Record<string, unknown>): void;
  /**
   * Increment a metric counter
   * @param metric - Metric name (e.g., 'wallet_connect_attempts')
   * @param value - Value to increment by (default: 1)
   * @since 0.3.0
   */
  increment?(metric: string, value?: number): void;
  /**
   * Set a gauge metric value
   * @param metric - Metric name
   * @param value - Current value
   * @since 0.3.0
   */
  gauge?(metric: string, value: number): void;
  /**
   * Flush buffered metrics to backend
   * @since 0.3.0
   */
  flush?(): Promise<void>;
  /**
   * Check if telemetry is enabled
   * @returns true if telemetry should be collected
   * @since 0.3.0
   */
  isEnabled?(): boolean;
}
/**
 * Crypto interface
 */
interface CryptoAdapter {
  encrypt(data: string, key: string): Promise<string>;
  decrypt(encrypted: string, key: string): Promise<string>;
  generateKey(): Promise<string>;
}
/**
 * Storage interface
 */
interface StorageAdapter {
  get(key: string): Promise<string | null>;
  set(key: string, value: string): Promise<void>;
  remove(key: string): Promise<void>;
  clear(): Promise<void>;
}
/**
 * Registry client interface (for adapters to query wallet info)
 */
interface RegistryClientAdapter {
  getWallet(walletId: WalletId): Promise<unknown>;
}
/**
 * Adapter context provided to all adapter methods
 */
interface AdapterContext {
  /** Application name */
  appName: string;
  /** Origin (for origin binding) */
  origin: string;
  /** Network */
  network: NetworkId;
  /** Logger */
  logger: LoggerAdapter;
  /** Telemetry (optional) */
  telemetry?: TelemetryAdapter;
  /** Registry client */
  registry: RegistryClientAdapter;
  /** Crypto adapter */
  crypto: CryptoAdapter;
  /** Storage adapter */
  storage: StorageAdapter;
  /** Timeout helper */
  timeout: (ms: number) => Promise<never>;
  /** Abort signal (for cancellation) */
  abortSignal?: AbortSignal;
}
/**
 * Adapter event names
 */
type AdapterEventName = 'connect' | 'disconnect' | 'sessionExpired' | 'txStatus' | 'error';
/**
 * Wallet adapter interface
 *
 * All wallet adapters must implement this interface.
 * Optional methods (marked with ?) should only be implemented
 * if the wallet supports that capability.
 */
interface WalletAdapter {
  /** Wallet identifier */
  readonly walletId: WalletId;
  /** Wallet display name */
  readonly name: string;
  /**
   * Get supported capabilities
   */
  getCapabilities(): CapabilityKey[];
  /**
   * Detect if wallet is installed
   */
  detectInstalled(): Promise<AdapterDetectResult>;
  /**
   * Connect to wallet
   * @param ctx Adapter context
   * @param opts Connection options (optional)
   */
  connect(
    ctx: AdapterContext,
    opts?: {
      timeoutMs?: number;
      partyId?: PartyId;
      /** When false, prefer remote/mobile transport over installed extension */
      preferInstalled?: boolean;
      /**
       * Called with a pairing/display URI (e.g. a WalletConnect `wc:` URI) as
       * soon as the adapter produces one, before the user approves. Lets the
       * connect UI render a QR / deep-link itself. Adapters that have no such
       * URI (their own SDK shows the QR) simply never call it.
       */
      onDisplayUri?: (uri: string) => void;
    }
  ): Promise<AdapterConnectResult>;
  /**
   * Disconnect from wallet
   * @param ctx Adapter context
   * @param session Session to disconnect
   */
  disconnect(ctx: AdapterContext, session: Session): Promise<void>;
  /**
   * Restore session (optional - only if wallet supports it)
   * @param ctx Adapter context
   * @param persisted Persisted session data
   */
  restore?(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>;
  /**
   * Sign message (optional - only if wallet supports it)
   * @param ctx Adapter context
   * @param session Active session
   * @param params Sign message parameters
   */
  signMessage?(
    ctx: AdapterContext,
    session: Session,
    params: SignMessageParams
  ): Promise<SignedMessage>;
  /**
   * Sign transaction (optional - only if wallet supports it)
   * @param ctx Adapter context
   * @param session Active session
   * @param params Sign transaction parameters
   */
  signTransaction?(
    ctx: AdapterContext,
    session: Session,
    params: SignTransactionParams
  ): Promise<SignedTransaction>;
  /**
   * Submit transaction (optional - only if wallet supports it)
   * @param ctx Adapter context
   * @param session Active session
   * @param params Submit transaction parameters
   */
  submitTransaction?(
    ctx: AdapterContext,
    session: Session,
    params: SubmitTransactionParams
  ): Promise<TxReceipt>;
  /**
   * Proxy a JSON Ledger API request (optional - only if wallet supports it)
   * @param ctx Adapter context
   * @param session Active session
   * @param params Ledger API request parameters
   */
  ledgerApi?(
    ctx: AdapterContext,
    session: Session,
    params: LedgerApiParams
  ): Promise<LedgerApiResult>;
  /**
   * Subscribe to adapter events (optional)
   * @param event Event name
   * @param handler Event handler
   * @returns Unsubscribe function
   */
  on?(event: AdapterEventName, handler: (payload: unknown) => void): () => void;
}
/**
 * Structural ("duck-type") match for the official
 * `@canton-network/core-wallet-discovery` `ProviderAdapter` shape.
 *
 * We deliberately do NOT import `@canton-network/*` (mirroring the stance in
 * `@partylayer/provider`'s extension-channel) — the standard's SHAPE is the
 * contract, not its package. An app supplies a concrete instance (e.g.
 * `new WalleyAdapter()`) and the SDK bridges it generically via
 * `GenericDiscoveryAdapter`, so a popup/remote wallet that neither injects
 * `window.canton` nor announces can still be hosted by the generic layer with
 * NO wallet-specific adapter package. Any standards-compliant wallet shipping
 * this shape inherits the capability.
 *
 * `provider()` returns a `CIP0103Provider` (the official `Provider<RpcTypes>`
 * already exposes `request`/`on`/`emit`/`removeListener`); the host/network are
 * baked into the app-supplied adapter at construction, so the bridge never sees
 * or sets them.
 */
interface OfficialProviderAdapter {
  /** Stable provider identity (e.g. "walley"). */
  readonly providerId: string;
  /** Display name (e.g. "Walley"). */
  readonly name: string;
  /** Provider transport kind, if surfaced ('browser' | 'desktop' | 'mobile' | 'remote'). */
  readonly type?: string;
  /** Branding icon (URL or data URI), if surfaced. */
  readonly icon?: string;
  /** Install/availability probe — popup-free. */
  detect(): Promise<boolean>;
  /** The live provider (CIP-0103-shaped: request/on/emit/removeListener). */
  provider(): CIP0103Provider;
  /** Optional session restore (returns a restored provider, or null). */
  restore?(): Promise<CIP0103Provider | null>;
  /** Optional teardown. */
  teardown?(): void;
}
/**
 * Structural guard for {@link OfficialProviderAdapter}. Checks only the
 * required surface (`providerId` string + `detect`/`provider` functions); the
 * returned `provider()` value is separately validated against the
 * `CIP0103Provider` duck-type by the consumer.
 */
declare function isOfficialProviderAdapter(value: unknown): value is OfficialProviderAdapter;
/**
 * Check if adapter supports required capabilities
 * Throws CapabilityNotSupportedError if not supported
 */
declare function capabilityGuard(
  adapter: WalletAdapter,
  requiredCapabilities: CapabilityKey[]
): void;
/**
 * Check if wallet is installed
 * Throws WalletNotInstalledError if not installed
 */
declare function installGuard(adapter: WalletAdapter): Promise<void>;

/**
 * Session management utilities
 */

/**
 * Generate a unique session ID
 */
declare function generateSessionId(): SessionId;
/**
 * Validate session structure
 */
declare function validateSession(session: unknown): session is Session;
/**
 * Check if session is expired
 */
declare function isSessionExpired(session: Session): boolean;
/**
 * Create a session with default values
 */
declare function createSession(
  walletId: string,
  partyId: string,
  network: string,
  origin: string,
  capabilities?: string[],
  expiresInMs?: number
): Session;

/**
 * Standards-first CIP-0103 wallet detection.
 *
 * The registry stores `providerDetection` rules per wallet entry. At
 * runtime the picker calls `window.canton.request({method:'status'})`,
 * receives the wallet's self-reported identity (kernel.id / kernel.url /
 * kernel.userUrl / kernel.clientType), and asks `findMatchingWallet`
 * which registry entry — if any — claims this provider.
 *
 * The architecture deliberately avoids hardcoding wallet IDs anywhere
 * outside the registry. Adding a new CIP-0103 wallet to the ecosystem
 * is a registry JSON update; no SDK release is required.
 */

/**
 * The shape of a CIP-0103 status response that detection cares about.
 *
 * Mirrors what `window.canton.request({ method: 'status' })` returns —
 * declared structurally so adapter packages can reuse this without
 * reaching into the wallet-specific types.
 */
interface Cip0103StatusForDetection {
  kernel?: {
    id?: string;
    url?: string;
    userUrl?: string;
    clientType?: string;
  };
}
/** Returns true if the runtime status matches any of the detection's matchers. */
declare function matchesProviderDetection(
  status: Cip0103StatusForDetection | null | undefined,
  detection: ProviderDetection | undefined
): boolean;
/**
 * Find the first registry entry whose `providerDetection` matches the
 * runtime status. Entries without `providerDetection` are skipped.
 *
 * Accepts either the raw `RegistryWalletEntry[]` shape (registry-client's
 * native input) or the converted `WalletInfo[]` shape that flows through
 * the SDK / React layer — the only field read is `providerDetection`,
 * which both shapes carry post-conversion.
 */
declare function findMatchingWallet<
  T extends {
    providerDetection?: ProviderDetection;
  },
>(status: Cip0103StatusForDetection | null | undefined, registry: readonly T[]): T | undefined;
/**
 * Type-guard convenience for the WalletInfo shape, since the SDK exposes
 * `WalletInfo[]` to React consumers.
 */
declare function findMatchingWalletInfo(
  status: Cip0103StatusForDetection | null | undefined,
  wallets: readonly WalletInfo[]
): WalletInfo | undefined;
/**
 * Best-effort display name for an unrecognised CIP-0103 provider. Reads
 * the wallet's self-declared `kernel.userUrl` (the human-facing URL
 * surfaced by Sigilry-style wallets) and falls back to `kernel.id` or
 * a generic label.
 */
declare function deriveGenericWalletName(
  status: Cip0103StatusForDetection | null | undefined
): string;

/**
 * Transport layer types for wallet communication
 *
 * Supports deep link, popup, and postMessage transports for mobile and web wallets.
 */

/**
 * Transport type
 */
type TransportType = 'deeplink' | 'popup' | 'postmessage' | 'injected';
/**
 * Transport options
 */
interface TransportOptions {
  /** Timeout in milliseconds */
  timeoutMs?: number;
  /** Allowed callback origins */
  allowedOrigins?: string[];
  /** Current origin for validation */
  origin: string;
}
/**
 * Connect request payload
 */
interface ConnectRequest {
  appName: string;
  origin: string;
  network: string;
  requestedCapabilities?: string[];
  state: string;
  redirectUri?: string;
}
/**
 * Connect response payload
 */
interface ConnectResponse {
  state: string;
  partyId?: PartyId;
  sessionToken?: string;
  expiresAt?: number;
  capabilities?: string[];
  error?: {
    code: string;
    message: string;
  };
}
/**
 * Sign request payload
 */
interface SignRequest {
  message?: string;
  transaction?: unknown;
  state: string;
  redirectUri?: string;
}
/**
 * Sign response payload
 */
interface SignResponse {
  state: string;
  signature?: string;
  transactionHash?: string;
  jobId?: string;
  error?: {
    code: string;
    message: string;
  };
}
/**
 * Job status (for async approval flows)
 */
interface JobStatus {
  jobId: string;
  status: 'pending' | 'approved' | 'denied' | 'expired';
  result?: {
    signature?: string;
    transactionHash?: string;
  };
  error?: {
    code: string;
    message: string;
  };
}
/**
 * Transport interface
 */
interface Transport$1 {
  /**
   * Open a connection request
   */
  openConnectRequest(
    url: string,
    request: ConnectRequest,
    options: TransportOptions
  ): Promise<ConnectResponse>;
  /**
   * Open a sign request
   */
  openSignRequest(
    url: string,
    request: SignRequest,
    options: TransportOptions
  ): Promise<SignResponse>;
  /**
   * Poll job status (if supported)
   */
  pollJobStatus?(jobId: string, statusUrl: string, options: TransportOptions): Promise<JobStatus>;
}

/**
 * Canonical Metrics Constants
 *
 * These metric names are the official set for PartyLayer telemetry.
 * Changing these names would break metrics aggregation and downstream reporting.
 *
 * @since 0.3.0
 */
/**
 * Enablement Metrics
 *
 * These metrics measure how PartyLayer enables wallet interactions.
 */
declare const ENABLEMENT_METRICS: {
  /** Total wallet connect() calls made */
  readonly WALLET_CONNECT_ATTEMPTS: 'wallet_connect_attempts';
  /** Successful wallet connections (session:connected events) */
  readonly WALLET_CONNECT_SUCCESS: 'wallet_connect_success';
  /** New sessions created (not restored) */
  readonly SESSIONS_CREATED: 'sessions_created';
  /** Sessions successfully restored from storage */
  readonly SESSIONS_RESTORED: 'sessions_restored';
  /** Total session restore attempts */
  readonly RESTORE_ATTEMPTS: 'restore_attempts';
};
/**
 * Error Metrics
 *
 * These metrics track error occurrences by code.
 */
declare const ERROR_METRICS: {
  /** Prefix for error metrics (e.g., error_USER_REJECTED) */
  readonly ERROR_PREFIX: 'error_';
};
/**
 * Registry Metrics
 *
 * These metrics track registry client behavior.
 */
declare const REGISTRY_METRICS: {
  /** Registry fetched from network */
  readonly REGISTRY_FETCH: 'registry_fetch';
  /** Registry served from cache */
  readonly REGISTRY_CACHE_HIT: 'registry_cache_hit';
  /** Stale registry was used */
  readonly REGISTRY_STALE: 'registry_stale';
};
/**
 * All metrics combined
 */
declare const METRICS: {
  /** Registry fetched from network */
  readonly REGISTRY_FETCH: 'registry_fetch';
  /** Registry served from cache */
  readonly REGISTRY_CACHE_HIT: 'registry_cache_hit';
  /** Stale registry was used */
  readonly REGISTRY_STALE: 'registry_stale';
  /** Prefix for error metrics (e.g., error_USER_REJECTED) */
  readonly ERROR_PREFIX: 'error_';
  /** Total wallet connect() calls made */
  readonly WALLET_CONNECT_ATTEMPTS: 'wallet_connect_attempts';
  /** Successful wallet connections (session:connected events) */
  readonly WALLET_CONNECT_SUCCESS: 'wallet_connect_success';
  /** New sessions created (not restored) */
  readonly SESSIONS_CREATED: 'sessions_created';
  /** Sessions successfully restored from storage */
  readonly SESSIONS_RESTORED: 'sessions_restored';
  /** Total session restore attempts */
  readonly RESTORE_ATTEMPTS: 'restore_attempts';
};
/**
 * Type for all metric names
 */
type MetricName = (typeof METRICS)[keyof typeof METRICS];
/**
 * Build an error metric name from an error code
 *
 * @param errorCode - The error code (e.g., 'USER_REJECTED')
 * @returns The metric name (e.g., 'error_USER_REJECTED')
 */
declare function errorMetricName(errorCode: string): string;

/**
 * Metrics Payload Types and Privacy Validation
 *
 * This module defines the privacy-safe payload format for metrics collection.
 *
 * Privacy Guarantees:
 * - NO wallet addresses
 * - NO raw party IDs
 * - NO transaction payloads
 * - NO signed message content
 * - NO user identifiers
 *
 * @since 0.3.0
 */
/**
 * Privacy-safe metrics payload
 *
 * This is the only payload format accepted by the metrics backend.
 */
interface MetricsPayload {
  /** SDK version (e.g., '0.3.0') */
  sdkVersion: string;
  /** Network identifier (e.g., 'devnet', 'mainnet') */
  network: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Metric name → value map */
  metrics: Record<string, number>;
  /** Hashed app identifier (opt-in, SHA-256) */
  appIdHash?: string;
  /** Hashed origin (opt-in, SHA-256) */
  originHash?: string;
}
/**
 * Validate that a payload is privacy-safe
 *
 * @param payload - Unknown payload to validate
 * @returns true if payload is valid MetricsPayload with no PII
 * @throws Error if forbidden fields are detected
 */
declare function validatePayload(payload: unknown): payload is MetricsPayload;
/**
 * Hash a string using SHA-256 (browser-compatible)
 *
 * @param value - String to hash
 * @returns Hex-encoded SHA-256 hash
 */
declare function hashForPrivacy(value: string): Promise<string>;
/**
 * Create a sanitized metrics payload
 *
 * This function ensures the payload is privacy-safe before sending.
 *
 * @param data - Raw metrics data
 * @returns Sanitized MetricsPayload
 */
declare function createMetricsPayload(data: {
  sdkVersion: string;
  network: string;
  metrics: Record<string, number>;
  appIdHash?: string;
  originHash?: string;
}): MetricsPayload;

/**
 * CAIP-2 Network Identity Utilities
 *
 * All CIP-0103 network identifiers use CAIP-2 format: "namespace:reference"
 * e.g. "canton:da-mainnet", "canton:da-devnet"
 *
 * Reference: https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-2.md
 */

declare const CANTON_NETWORKS: Record<string, string>;
/**
 * Convert a legacy PartyLayer NetworkId (e.g. "devnet") or already-CAIP-2
 * string to a CIP-0103 Network object.
 *
 * @throws {Error} if the resulting network ID is not valid CAIP-2
 */
declare function toCAIP2Network(networkId: string): CIP0103Network;
/**
 * Extract the short network name from a CAIP-2 ID.
 * Returns the original string if no reverse mapping exists.
 */
declare function fromCAIP2Network(caip2: string): string;
/**
 * Validate that a string conforms to CAIP-2 format.
 *
 * CAIP-2 format: namespace:reference
 * - namespace: [-a-z0-9]{3,8}
 * - reference: [-_a-zA-Z0-9]{1,32}
 */
declare function isValidCAIP2(networkId: string): boolean;
/**
 * Detect a confident, recognized, DIFFERENT-network mismatch between an
 * `expected` (dApp-configured) and `actual` (wallet-reported) network.
 *
 * Conservative by design — returns `null` (no mismatch) unless BOTH networks
 * normalize to recognized well-known Canton CAIP-2 ids AND differ. Unparseable
 * or unrecognized/custom networks → `null` (never a false positive).
 */
declare function detectNetworkMismatch(
  expected: string,
  actual: string
): {
  expected: string;
  actual: string;
} | null;

/**
 * Deep Link Transport
 *
 * Opens a deep link URL (mobile) and awaits callback via redirect or postMessage.
 *
 * Security:
 * - State parameter (nonce) for CSRF protection
 * - Origin validation
 * - Timeout enforcement
 * - Callback origin allowlist
 */

/**
 * Deep link transport implementation
 */
declare class DeepLinkTransport implements Transport$1 {
  /**
   * Generate a random state nonce
   */
  private generateState;
  /**
   * Build deep link URL with query parameters
   */
  private buildDeepLinkUrl;
  /**
   * Validate callback origin
   */
  private validateOrigin;
  /**
   * Wait for callback via postMessage or redirect
   */
  private waitForCallback;
  /**
   * Open a connection request
   */
  openConnectRequest(
    url: string,
    request: ConnectRequest,
    options: TransportOptions
  ): Promise<ConnectResponse>;
  /**
   * Open a sign request
   */
  openSignRequest(
    url: string,
    request: SignRequest,
    options: TransportOptions
  ): Promise<SignResponse>;
}

/**
 * Popup Transport
 *
 * Opens a centered popup window and establishes a postMessage channel.
 *
 * Security:
 * - Origin validation
 * - State parameter validation
 * - Popup window management
 */

/**
 * Popup transport implementation
 */
declare class PopupTransport implements Transport$1 {
  /**
   * Generate a random state nonce
   */
  private generateState;
  /**
   * Build URL with query parameters
   */
  private buildUrl;
  /**
   * Validate message origin
   */
  private validateOrigin;
  /**
   * Open popup window
   */
  private openPopup;
  /**
   * Wait for postMessage callback
   */
  private waitForCallback;
  /**
   * Open a connection request
   */
  openConnectRequest(
    url: string,
    request: ConnectRequest,
    options: TransportOptions
  ): Promise<ConnectResponse>;
  /**
   * Open a sign request
   */
  openSignRequest(
    url: string,
    request: SignRequest,
    options: TransportOptions
  ): Promise<SignResponse>;
}

/**
 * PostMessage Transport
 *
 * Establishes a postMessage channel with an existing window/iframe.
 *
 * Security:
 * - Origin validation
 * - State parameter validation
 */

/**
 * PostMessage transport implementation
 */
declare class PostMessageTransport implements Transport$1 {
  /**
   * Generate a random state nonce
   */
  private generateState;
  /**
   * Validate message origin
   */
  private validateOrigin;
  /**
   * Send message and wait for response
   */
  private sendAndWait;
  /**
   * Open a connection request
   */
  openConnectRequest(
    url: string,
    request: ConnectRequest,
    options: TransportOptions
  ): Promise<ConnectResponse>;
  /**
   * Open a sign request
   */
  openSignRequest(
    url: string,
    request: SignRequest,
    options: TransportOptions
  ): Promise<SignResponse>;
}

/**
 * Mock Transport
 *
 * For testing and development. Simulates transport behavior without real network calls.
 */

/**
 * Mock transport implementation
 */
declare class MockTransport implements Transport$1 {
  private mockResponses;
  private mockJobs;
  /**
   * Set mock response for a state
   */
  setMockResponse(state: string, response: ConnectResponse | SignResponse): void;
  /**
   * Set mock job status
   */
  setMockJob(jobId: string, status: JobStatus): void;
  /**
   * Clear all mocks
   */
  clearMocks(): void;
  /**
   * Open a connection request (mock)
   */
  openConnectRequest(
    _url: string,
    request: ConnectRequest,
    _options: TransportOptions
  ): Promise<ConnectResponse>;
  /**
   * Open a sign request (mock)
   */
  openSignRequest(
    _url: string,
    request: SignRequest,
    _options: TransportOptions
  ): Promise<SignResponse>;
  /**
   * Poll job status (mock)
   */
  pollJobStatus(jobId: string, _statusUrl: string, _options: TransportOptions): Promise<JobStatus>;
}

/**
 * Transport abstractions for wallet communication
 */
/**
 * Transport message
 */
interface TransportMessage<T = unknown> {
  /** Message ID */
  id: string;
  /** Message type */
  type: string;
  /** Message payload */
  payload: T;
  /** Timestamp */
  timestamp: number;
  /** Origin */
  origin?: string;
}
/**
 * Transport response
 */
interface TransportResponse<T = unknown> {
  /** Response ID (matches request ID) */
  id: string;
  /** Success flag */
  success: boolean;
  /** Response data (if success) */
  data?: T;
  /** Error (if not success) */
  error?: {
    code: string;
    message: string;
  };
}
/**
 * Transport interface for wallet communication
 * Different wallets may use different transports (postMessage, WebSocket, HTTP, etc.)
 */
interface Transport {
  /**
   * Send a message and wait for response
   */
  send<TRequest = unknown, TResponse = unknown>(
    message: TransportMessage<TRequest>
  ): Promise<TransportResponse<TResponse>>;
  /**
   * Subscribe to incoming messages
   */
  onMessage(handler: (message: TransportMessage) => void): () => void;
  /**
   * Check if transport is connected
   */
  isConnected(): boolean;
  /**
   * Connect the transport
   */
  connect(): Promise<void>;
  /**
   * Disconnect the transport
   */
  disconnect(): Promise<void>;
}

export {
  type AdapterConnectResult,
  type AdapterContext,
  type AdapterDetectResult,
  type AdapterEventName,
  type AdapterMetadata,
  type AdapterTransport,
  CANTON_NETWORKS,
  type CIP0103Account,
  type CIP0103AccountStatus,
  type CIP0103ConnectResult,
  type CIP0103Event,
  type CIP0103EventListener,
  type CIP0103LedgerApiRequest,
  type CIP0103LedgerApiResponse,
  type CIP0103Method,
  type CIP0103Network,
  type CIP0103Provider,
  type CIP0103ProviderInfo,
  type CIP0103ProviderRpcError,
  type CIP0103ProviderType,
  type CIP0103RequestParams,
  type CIP0103RequestPayload,
  type CIP0103SignMessageRequest,
  type CIP0103StatusEvent,
  type CIP0103TxChangedEvent,
  type CIP0103TxExecutedPayload,
  type CIP0103TxFailedPayload,
  type CIP0103TxPendingPayload,
  type CIP0103TxSignedPayload,
  type CIP0103TxStatus,
  CIP0103_EVENTS,
  CIP0103_MANDATORY_METHODS,
  CIP0103_METHODS,
  type CapabilityKey,
  CapabilityNotSupportedError,
  type Cip0103StatusForDetection,
  type Cip0103Support,
  type ConnectRequest,
  type ConnectResponse,
  type CryptoAdapter,
  DeepLinkTransport,
  ENABLEMENT_METRICS,
  ERROR_METRICS,
  type ErrorCode,
  type ErrorMappingContext,
  type InstallHints,
  InternalError,
  type JobStatus,
  type LedgerApiParams,
  type LedgerApiResult,
  type LoggerAdapter,
  METRICS,
  type MetricName,
  type MetricsPayload,
  MockTransport,
  type NetworkId,
  NetworkMismatchError,
  type OfficialProviderAdapter,
  OriginNotAllowedError,
  type PartyId,
  PartyLayerError,
  type PersistedSession,
  PopupTransport,
  PostMessageTransport,
  type ProviderDetection,
  type ProviderMatcher,
  REGISTRY_METRICS,
  type RegistryClientAdapter,
  RegistryFetchFailedError,
  RegistrySchemaInvalidError,
  RegistryVerificationFailedError,
  type Session,
  SessionExpiredError,
  type SessionId,
  type SignMessageParams,
  type SignRequest,
  type SignResponse,
  type SignTransactionParams,
  type Signature,
  type SignedMessage,
  type SignedTransaction,
  type StorageAdapter,
  type SubmitTransactionParams,
  type TelemetryAdapter,
  TimeoutError,
  type TransactionHash,
  type TransactionStatus,
  type Transport,
  TransportError,
  type TransportOptions,
  type TransportType,
  type TxReceipt,
  type TxStatusUpdate,
  UserRejectedError,
  type WalletAdapter,
  type WalletId,
  type WalletInfo,
  WalletNotFoundError,
  WalletNotInstalledError,
  capabilityGuard,
  createMetricsPayload,
  createSession,
  deriveGenericWalletName,
  detectNetworkMismatch,
  errorMetricName,
  findMatchingWallet,
  findMatchingWalletInfo,
  fromCAIP2Network,
  generateSessionId,
  hashForPrivacy,
  installGuard,
  isCip0103Native,
  isOfficialProviderAdapter,
  isSessionExpired,
  isValidCAIP2,
  mapUnknownErrorToPartyLayerError,
  matchesProviderDetection,
  toCAIP2Network,
  toPartyId,
  toSessionId,
  toSignature,
  toTransactionHash,
  toWalletId,
  validatePayload,
  validateSession,
};
