// API SURFACE SNAPSHOT — @partylayer/provider
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class CIP0103EventBus { private listeners; private owner; setOwner(owner: CIP0103Provider): void; on<T = unknown>(event: string, listener: CIP0103EventListener<T>): CIP0103Provider; emit<T = unknown>(event: string, ...args: T[]): boolean; removeListener<T = unknown>(event: string, listenerToRemove: CIP0103EventListener<T>): CIP0103Provider; removeAllListeners(event?: string): void; listenerCount(event: string): number; }
declare class MethodRouter { private handlers; private walletProvider; constructor(); setWalletProvider(provider: CIP0103Provider | null): void; getWalletProvider(): CIP0103Provider | null; register<T>(method: string, handler: MethodHandler<T>): void; route<T>(payload: CIP0103RequestPayload): Promise<T>; hasHandler(method: string): boolean; private registerDefaults; }
declare class PartyLayerProvider implements CIP0103Provider { private readonly eventBus; private readonly router; private readonly options; private nativeProvider; private connected; private nativeForwarders; constructor(options?: PartyLayerProviderOptions); request<T = unknown>(args: CIP0103RequestPayload): Promise<T>; on<T = unknown>(event: string, listener: CIP0103EventListener<T>): this; emit<T = unknown>(event: string, ...args: T[]): boolean; removeListener<T = unknown>(event: string, listenerToRemove: CIP0103EventListener<T>): this; get isConnected(): boolean; setWalletProvider(discovered: DiscoveredProvider): void; getNativeProvider(): CIP0103Provider | null; destroy(): void; private registerOrchestratedMethods; private forwardNativeEvents; private unforwardNativeEvents; private emitStatusChanged; }
declare class ProviderRpcError extends Error { readonly code: number; readonly data?: unknown; constructor(message: string, code: number, data?: unknown); toJSON(): Record<string, unknown>; }
declare const JSON_RPC_ERRORS: { readonly PARSE_ERROR: -32700; readonly INVALID_REQUEST: -32600; readonly METHOD_NOT_FOUND: -32601; readonly INVALID_PARAMS: -32602; readonly INTERNAL_ERROR: -32603; readonly INVALID_INPUT: -32000; readonly RESOURCE_NOT_FOUND: -32001; readonly RESOURCE_UNAVAILABLE: -32002; readonly TRANSACTION_REJECTED: -32003; readonly METHOD_NOT_SUPPORTED: -32004; readonly RATE_LIMIT_EXCEEDED: -32005; };
declare const RPC_ERRORS: { readonly USER_REJECTED: 4001; readonly UNAUTHORIZED: 4100; readonly UNSUPPORTED_METHOD: 4200; readonly DISCONNECTED: 4900; readonly CHAIN_DISCONNECTED: 4901; };
declare function chainDisconnected(message?: string): ProviderRpcError;
declare function createExtensionChannelProvider(options?: ExtensionChannelOptions): CIP0103Provider;
declare function createProviderBridge(client: BridgeableClient): CIP0103Provider;
declare function disconnected(message?: string): ProviderRpcError;
declare function discoverAnnouncedProviders(options?: AnnounceDiscoveryOptions): Promise<DiscoveredProvider[]>;
declare function discoverInjectedProviders(): DiscoveredProvider[];
declare function discoverProviders(options?: AnnounceDiscoveryOptions): Promise<DiscoveredProvider[]>;
declare function handleAsyncConnect(walletProvider: CIP0103Provider, connectResult: CIP0103ConnectResult, options?: AsyncConnectOptions): Promise<CIP0103ConnectResult>;
declare function handleAsyncPrepareExecute(walletProvider: CIP0103Provider, commandId: string, userUrl: string | undefined, options?: AsyncPrepareExecuteOptions): Promise<CIP0103TxChangedEvent>;
declare function internalError(message: string, data?: unknown): ProviderRpcError;
declare function invalidParams(message: string, data?: unknown): ProviderRpcError;
declare function isCIP0103Provider(obj: unknown): obj is CIP0103Provider;
declare function methodNotFound(method: string): ProviderRpcError;
declare function resourceNotFound(message: string, data?: unknown): ProviderRpcError;
declare function resourceUnavailable(message: string, data?: unknown): ProviderRpcError;
declare function subscribeAnnouncedProviders(onProvider: (provider: DiscoveredProvider) => void, options?: AnnounceSubscribeOptions): () => void;
declare function toPartyLayerError(err: ProviderRpcError): PartyLayerError;
declare function toProviderRpcError(err: unknown): ProviderRpcError;
declare function transactionRejected(message?: string, data?: unknown): ProviderRpcError;
declare function unauthorized(message?: string, data?: unknown): ProviderRpcError;
declare function unsupportedMethod(method: string): ProviderRpcError;
declare function userRejected(message?: string, data?: unknown): ProviderRpcError;
declare function waitForAnnouncedProvider(predicate: (provider: DiscoveredProvider) => boolean, options?: WaitForAnnouncedOptions): Promise<DiscoveredProvider | null>;
declare function waitForProvider(id: string, timeoutMs?: number): Promise<DiscoveredProvider | null>;
export { CANTON_NETWORKS, CIP0103Account, CIP0103AccountStatus, CIP0103ConnectResult, CIP0103Event, CIP0103EventListener, CIP0103LedgerApiRequest, CIP0103LedgerApiResponse, CIP0103Method, CIP0103Network, CIP0103Provider, CIP0103ProviderInfo, CIP0103ProviderRpcError, CIP0103ProviderType, CIP0103RequestParams, CIP0103RequestPayload, CIP0103SignMessageRequest, CIP0103StatusEvent, CIP0103TxChangedEvent, CIP0103TxExecutedPayload, CIP0103TxFailedPayload, CIP0103TxPendingPayload, CIP0103TxSignedPayload, CIP0103TxStatus, CIP0103_EVENTS, CIP0103_MANDATORY_METHODS, CIP0103_METHODS, fromCAIP2Network, isValidCAIP2, toCAIP2Network } from '@partylayer/core';
export { type AnnounceDiscoveryOptions, type AnnounceSubscribeOptions, type AnnouncedWallet, type AsyncConnectOptions, type AsyncPrepareExecuteOptions, type BridgeableClient, CIP0103EventBus, type DiscoveredProvider, type ExtensionChannelOptions, JSON_RPC_ERRORS, type MethodHandler, MethodRouter, PartyLayerProvider, type PartyLayerProviderOptions, ProviderRpcError, RPC_ERRORS, type WaitForAnnouncedOptions, chainDisconnected, createExtensionChannelProvider, createProviderBridge, disconnected, discoverAnnouncedProviders, discoverInjectedProviders, discoverProviders, handleAsyncConnect, handleAsyncPrepareExecute, internalError, invalidParams, isCIP0103Provider, methodNotFound, resourceNotFound, resourceUnavailable, subscribeAnnouncedProviders, toPartyLayerError, toProviderRpcError, transactionRejected, unauthorized, unsupportedMethod, userRejected, waitForAnnouncedProvider, waitForProvider };
import { CIP0103Provider, CIP0103RequestPayload, CIP0103EventListener, PartyLayerError, CIP0103ConnectResult, CIP0103TxChangedEvent, CIP0103RequestParams } from '@partylayer/core';
interface AnnounceDiscoveryOptions { timeoutMs?: number; createProvider?: (announced: AnnouncedWallet) => CIP0103Provider | Promise<CIP0103Provider>; }
interface AnnounceSubscribeOptions { createProvider?: (announced: AnnouncedWallet) => CIP0103Provider | Promise<CIP0103Provider>; requestOnSubscribe?: boolean; }
interface AnnouncedWallet { id: string; name?: string; icon?: string; target?: string; }
interface AsyncConnectOptions { timeoutMs?: number; onUserUrl?: (url: string) => void; }
interface AsyncPrepareExecuteOptions { timeoutMs?: number; onUserUrl?: (url: string) => void; }
interface BridgeableClient { connect(options?: unknown): Promise<{ sessionId: unknown; walletId: unknown; partyId: unknown; network: string; expiresAt?: number; capabilitiesSnapshot?: string[]; }>; disconnect(): Promise<void>; getActiveSession(): Promise<{ sessionId: unknown; walletId: unknown; partyId: unknown; network: string; expiresAt?: number; capabilitiesSnapshot?: string[]; } | null>; signMessage(params: { message: string; nonce?: string; domain?: string; }): Promise<{ signature: unknown; }>; signTransaction(params: { tx: unknown; }): Promise<{ transactionHash: unknown; signedTx?: unknown; partyId?: unknown; }>; submitTransaction(params: { signedTx: unknown; }): Promise<{ transactionHash: unknown; submittedAt?: number; commandId?: string; updateId?: string; }>; ledgerApi?(params: { requestMethod: string; resource: string; body?: string | Record<string, unknown>; }): Promise<{ response: string; }>; getRegistryStatus(): unknown; on(event: string, handler: (event: unknown) => void | Promise<void>): () => void; }
interface DiscoveredProvider { id: string; provider: CIP0103Provider; source: 'injected' | 'registry'; isAsync?: boolean; name?: string; icon?: string; identityResolved?: boolean; }
interface ExtensionChannelOptions { target?: string; timeoutMs?: number; }
interface PartyLayerProviderOptions { walletProvider?: DiscoveredProvider; asyncTimeoutMs?: number; onUserUrl?: (url: string) => void; }
interface WaitForAnnouncedOptions extends AnnounceSubscribeOptions { timeoutMs?: number; }
type MethodHandler<T = unknown> = (walletProvider: CIP0103Provider, params?: CIP0103RequestParams) => Promise<T>;
