// API SURFACE SNAPSHOT — @partylayer/react/query
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare const partyLayerKeys: { readonly all: readonly [ "partylayer" ]; readonly connect: () => readonly [ "partylayer", "connect" ]; readonly account: () => readonly [ "partylayer", "account" ]; readonly session: () => readonly [ "partylayer", "session" ]; readonly wallets: (params?: { filter?: unknown; }) => readonly [ "partylayer", "wallets", { filter?: unknown; } ]; readonly registryStatus: () => readonly [ "partylayer", "registryStatus" ]; };
declare function useConnect(parameters?: UseConnectParameters): UseConnectReturnType;
export { type ConnectVariables, type PartyLayerKeys, type UseConnectParameters, type UseConnectReturnType, partyLayerKeys, useConnect };
import { ConnectOptions, Session } from '@partylayer/sdk';
import { UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
interface UseConnectParameters { mutation?: Omit<UseMutationOptions<Session, Error, ConnectVariables>, 'mutationFn' | 'mutationKey'>; }
type ConnectVariables = ConnectOptions | undefined;
type PartyLayerKeys = typeof partyLayerKeys;
type UseConnectReturnType = UseMutationResult<Session, Error, ConnectVariables> & { connect: UseMutationResult<Session, Error, ConnectVariables>['mutate']; connectAsync: UseMutationResult<Session, Error, ConnectVariables>['mutateAsync']; };
