// API SURFACE SNAPSHOT — @partylayer/provider
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import {
  CIP0103Provider,
  CIP0103RequestPayload,
  CIP0103EventListener,
  PartyLayerError,
  CIP0103ConnectResult,
  CIP0103TxChangedEvent,
  CIP0103RequestParams,
} from '@partylayer/core';
export {
  CANTON_NETWORKS,
  CIP0103Account,
  CIP0103AccountStatus,
  CIP0103ConnectResult,
  CIP0103Event,
  CIP0103EventListener,
  CIP0103LedgerApiRequest,
  CIP0103LedgerApiResponse,
  CIP0103Method,
  CIP0103Network,
  CIP0103Provider,
  CIP0103ProviderInfo,
  CIP0103ProviderRpcError,
  CIP0103ProviderType,
  CIP0103RequestParams,
  CIP0103RequestPayload,
  CIP0103SignMessageRequest,
  CIP0103StatusEvent,
  CIP0103TxChangedEvent,
  CIP0103TxExecutedPayload,
  CIP0103TxFailedPayload,
  CIP0103TxPendingPayload,
  CIP0103TxSignedPayload,
  CIP0103TxStatus,
  CIP0103_EVENTS,
  CIP0103_MANDATORY_METHODS,
  CIP0103_METHODS,
  fromCAIP2Network,
  isValidCAIP2,
  toCAIP2Network,
} from '@partylayer/core';

/**
 * CIP-0103 Wallet Discovery
 *
 * Discovers CIP-0103-compliant wallet Providers from the global scope.
 * Wallet-agnostic: no hardcoded wallet logic, only duck-type checking
 * for the Provider interface shape.
 */

/** Metadata about a discovered CIP-0103 wallet provider */
interface DiscoveredProvider {
  /** Identifier (e.g. "canton.console", "consoleWallet") */
  id: string;
  /** The native CIP-0103 Provider instance */
  provider: CIP0103Provider;
  /** How it was discovered */
  source: 'injected' | 'registry';
  /** Whether the provider supports async flows (userUrl) */
  isAsync?: boolean;
  /** Display name (if discoverable from status) */
  name?: string;
  /** Icon (data: URI or URL) — populated for announce-discovered wallets. */
  icon?: string;
  /**
   * Whether this entry's STABLE IDENTITY was resolved (additive; A2.1).
   *
   * - announce-discovered entries: always `true` — the announce `id` IS the
   *   wallet's real extension id (canonical provider.md: announce is the
   *   discovery path).
   * - injected (`window.canton` scan) entries: `true` only when a sync
   *   `provider.id` or a `status().provider.id` probe yielded a real id;
   *   `false` when discovery fell back to the path id (an identity-LESS bare
   *   slot, e.g. Console's `{request,on,emit,removeListener,source}` with no id).
   *
   * LIVE INCIDENT (partylayer.xyz post-A2): an identity-less bare slot resolved
   * to the path id `'canton'`; downstream that synthesized a phantom "Canton
   * Wallet" (`browser:ext:canton`) picker entry whose provider was the slot
   * itself. Consumers MUST drop unresolved injected entries rather than list
   * them — correctness must not depend on probe timing.
   */
  identityResolved?: boolean;
}
/**
 * Check if an object implements the CIP-0103 Provider interface.
 *
 * This is a structural (duck-type) check — it verifies the presence of
 * the four required methods without checking implementation correctness.
 */
declare function isCIP0103Provider(obj: unknown): obj is CIP0103Provider;
/**
 * Discover all injected CIP-0103 providers from the global scope.
 *
 * Scans well-known window paths and their sub-properties for objects
 * that implement the Provider interface.
 */
declare function discoverInjectedProviders(): DiscoveredProvider[];
/**
 * Wait for a specific provider to be injected (with timeout).
 *
 * Extensions may inject their provider after page load. This function
 * polls at 100ms intervals until the provider appears or the timeout
 * expires.
 *
 * @param id - Provider id to match (exact or suffix match)
 * @param timeoutMs - Maximum wait time (default 3000ms)
 */
declare function waitForProvider(
  id: string,
  timeoutMs?: number
): Promise<DiscoveredProvider | null>;
/** Metadata carried by a `canton:announceProvider` event. */
interface AnnouncedWallet {
  /** Stable provider id (extension id), e.g. "ldmoh…" for Send. */
  id: string;
  /** Display name. */
  name?: string;
  /** Icon (data: URI or URL). */
  icon?: string;
  /** Routing key for the extension postMessage channel. */
  target?: string;
}
interface AnnounceDiscoveryOptions {
  /** How long to collect announce replies after the request (ms). Default 300. */
  timeoutMs?: number;
  /**
   * Build a CIP-0103 provider from an announced wallet. Defaults to the
   * self-contained `createExtensionChannelProvider` (splice postMessage over
   * the `target` channel). Injectable so apps can substitute the official
   * `@canton-network/dapp-sdk` `ExtensionAdapter`, and tests a mock.
   */
  createProvider?: (announced: AnnouncedWallet) => CIP0103Provider | Promise<CIP0103Provider>;
}
/**
 * Discover wallets that advertise via `canton:announceProvider` (EIP-6963-style).
 *
 * Works regardless of who owns `window.canton` — this is how Send (and
 * Console-via-announce) are found. Each result is a working CIP-0103 provider.
 * Announce replies are deduped by id within a single call.
 */
declare function discoverAnnouncedProviders(
  options?: AnnounceDiscoveryOptions
): Promise<DiscoveredProvider[]>;
/**
 * Discover ALL CIP-0103 wallets: the synchronous `window.canton` scan PLUS the
 * `canton:announceProvider` handshake, MERGED and deduped by stable provider id.
 *
 * Dedup keys:
 *   - INJECTED entries: resolved via {@link resolveInjectedKey} (sync id →
 *     capped read-only status() probe → path id). Resolved in PARALLEL.
 *   - ANNOUNCE entries: their `d.id` (== announce id == target == the wallet's
 *     `provider.id`). NOT status-probed — an offline announce wallet (e.g. Send)
 *     would otherwise hang up to the channel timeout.
 *
 * INJECTED entries are processed FIRST so the direct `window.canton` provider
 * wins over the announce postMessage shim for a wallet reachable both ways
 * (e.g. Console announces AND owns `window.canton` → appears exactly once).
 *
 * Backward-compatible superset of `discoverInjectedProviders()` (left unchanged).
 */
declare function discoverProviders(
  options?: AnnounceDiscoveryOptions
): Promise<DiscoveredProvider[]>;

/**
 * PartyLayerProvider — CIP-0103 Native Provider Implementation
 *
 * This is the core Provider class. It wraps a single native CIP-0103
 * wallet provider and adds:
 *
 * - Method routing with orchestrated overrides (connect, disconnect, etc.)
 * - Event forwarding from the native wallet to the dApp
 * - Async wallet support (userUrl flows)
 * - Error normalization to ProviderRpcError
 * - Forward compatibility for unknown methods and events
 *
 * IMPORTANT: No wallet-specific logic lives here. The Provider is purely
 * a router and normalizer.
 */

interface PartyLayerProviderOptions {
  /** Discovered wallet provider to wrap */
  walletProvider?: DiscoveredProvider;
  /** Timeout for async operations (ms). Default 300_000 (5 min). */
  asyncTimeoutMs?: number;
  /** Callback when a userUrl is available (for async wallets) */
  onUserUrl?: (url: string) => void;
}
declare class PartyLayerProvider implements CIP0103Provider {
  private readonly eventBus;
  private readonly router;
  private readonly options;
  private nativeProvider;
  private connected;
  /** Event forwarders from the native provider, keyed by event name */
  private nativeForwarders;
  constructor(options?: PartyLayerProviderOptions);
  request<T = unknown>(args: CIP0103RequestPayload): Promise<T>;
  on<T = unknown>(event: string, listener: CIP0103EventListener<T>): this;
  emit<T = unknown>(event: string, ...args: T[]): boolean;
  removeListener<T = unknown>(event: string, listenerToRemove: CIP0103EventListener<T>): this;
  /** Whether the provider is currently in a connected state */
  get isConnected(): boolean;
  /** Switch the underlying wallet provider (e.g. user selects a different wallet) */
  setWalletProvider(discovered: DiscoveredProvider): void;
  /** Get the currently attached native provider (if any) */
  getNativeProvider(): CIP0103Provider | null;
  /** Tear down: unsubscribe all events and release the native provider */
  destroy(): void;
  private registerOrchestratedMethods;
  private forwardNativeEvents;
  private unforwardNativeEvents;
  /** Emit statusChanged by querying the current wallet provider status */
  private emitStatusChanged;
}

/**
 * PartyLayerClient → CIP-0103 Provider Bridge
 *
 * Creates a CIP-0103-compliant Provider backed by an existing
 * PartyLayerClient instance. This is the backward-compatibility path:
 * existing dApps using PartyLayerClient can obtain a standard Provider
 * without rewiring their wallet adapter stack.
 *
 * Usage:
 *   const provider = createProviderBridge(client);
 *   // or (added to PartyLayerClient):
 *   const provider = client.asProvider();
 */

/**
 * Minimal interface for the PartyLayerClient consumed by the bridge.
 * Using an interface avoids importing the full SDK (prevents circular deps).
 */
interface BridgeableClient {
  connect(options?: unknown): Promise<{
    sessionId: unknown;
    walletId: unknown;
    partyId: unknown;
    network: string;
    expiresAt?: number;
    capabilitiesSnapshot?: string[];
  }>;
  disconnect(): Promise<void>;
  getActiveSession(): Promise<{
    sessionId: unknown;
    walletId: unknown;
    partyId: unknown;
    network: string;
    expiresAt?: number;
    capabilitiesSnapshot?: string[];
  } | null>;
  signMessage(params: { message: string; nonce?: string; domain?: string }): Promise<{
    signature: unknown;
  }>;
  signTransaction(params: { tx: unknown }): Promise<{
    transactionHash: unknown;
    signedTx?: unknown;
    partyId?: unknown;
  }>;
  submitTransaction(params: { signedTx: unknown }): Promise<{
    transactionHash: unknown;
    submittedAt?: number;
    commandId?: string;
    updateId?: string;
  }>;
  ledgerApi?(params: { requestMethod: string; resource: string; body?: string }): Promise<{
    response: string;
  }>;
  getRegistryStatus(): unknown;
  on(event: string, handler: (event: unknown) => void | Promise<void>): () => void;
}
/**
 * Create a CIP-0103 Provider backed by a PartyLayerClient.
 *
 * All `request()` calls are mapped to PartyLayerClient methods.
 * PartyLayer events are forwarded as CIP-0103 events.
 */
declare function createProviderBridge(client: BridgeableClient): CIP0103Provider;

/**
 * CIP-0103 / EIP-1193 / EIP-1474 Error Model
 *
 * All errors on the Provider surface MUST be ProviderRpcError instances
 * with numeric codes. No PartyLayer string-based ErrorCode is ever exposed.
 *
 * Reference: https://eips.ethereum.org/EIPS/eip-1193
 * Reference: https://eips.ethereum.org/EIPS/eip-1474
 */
declare class ProviderRpcError extends Error {
  readonly code: number;
  readonly data?: unknown;
  constructor(message: string, code: number, data?: unknown);
  toJSON(): Record<string, unknown>;
}
declare const RPC_ERRORS: {
  /** User rejected the request */
  readonly USER_REJECTED: 4001;
  /** The requested method/account is not authorized */
  readonly UNAUTHORIZED: 4100;
  /** Provider does not support the requested method */
  readonly UNSUPPORTED_METHOD: 4200;
  /** Provider is disconnected from all chains */
  readonly DISCONNECTED: 4900;
  /** Provider is not connected to the requested chain */
  readonly CHAIN_DISCONNECTED: 4901;
};
declare const JSON_RPC_ERRORS: {
  /** Invalid JSON (parse error) */
  readonly PARSE_ERROR: -32700;
  /** Invalid request object */
  readonly INVALID_REQUEST: -32600;
  /** Method not found */
  readonly METHOD_NOT_FOUND: -32601;
  /** Invalid method parameters */
  readonly INVALID_PARAMS: -32602;
  /** Internal JSON-RPC error */
  readonly INTERNAL_ERROR: -32603;
  /** Invalid input / missing or invalid parameters */
  readonly INVALID_INPUT: -32000;
  /** Resource not found */
  readonly RESOURCE_NOT_FOUND: -32001;
  /** Resource unavailable */
  readonly RESOURCE_UNAVAILABLE: -32002;
  /** Transaction rejected */
  readonly TRANSACTION_REJECTED: -32003;
  /** Method not supported */
  readonly METHOD_NOT_SUPPORTED: -32004;
  /** Rate limit exceeded */
  readonly RATE_LIMIT_EXCEEDED: -32005;
};
declare function userRejected(message?: string, data?: unknown): ProviderRpcError;
declare function unauthorized(message?: string, data?: unknown): ProviderRpcError;
declare function unsupportedMethod(method: string): ProviderRpcError;
declare function disconnected(message?: string): ProviderRpcError;
declare function chainDisconnected(message?: string): ProviderRpcError;
declare function internalError(message: string, data?: unknown): ProviderRpcError;
declare function invalidParams(message: string, data?: unknown): ProviderRpcError;
declare function methodNotFound(method: string): ProviderRpcError;
declare function resourceNotFound(message: string, data?: unknown): ProviderRpcError;
declare function resourceUnavailable(message: string, data?: unknown): ProviderRpcError;
declare function transactionRejected(message?: string, data?: unknown): ProviderRpcError;

/**
 * Bidirectional error mapping between PartyLayer ErrorCode and CIP-0103 numeric codes
 *
 * This module ensures no PartyLayer internals leak through the Provider surface,
 * and provides a reverse path for the bridge.
 */

/**
 * Convert any error into a ProviderRpcError for the CIP-0103 surface.
 *
 * This is the single normalization point — every error that escapes
 * the Provider MUST pass through this function.
 */
declare function toProviderRpcError(err: unknown): ProviderRpcError;
/**
 * Convert ProviderRpcError back to a PartyLayerError.
 *
 * Used by the bridge path when errors from the Provider surface
 * need to flow back into the PartyLayerClient world.
 */
declare function toPartyLayerError(err: ProviderRpcError): PartyLayerError;

/**
 * Extension target-channel CIP-0103 provider.
 *
 * Builds a working CIP-0103 provider for a wallet discovered via
 * `canton:announceProvider` (see discovery.ts). Announce wallets route requests
 * over the splice-wallet postMessage protocol — the dApp posts a
 * `SPLICE_WALLET_REQUEST` on `window` and the extension replies with a
 * `SPLICE_WALLET_RESPONSE`, correlated by JSON-RPC id and routed by `target`.
 *
 * This is a self-contained, dependency-free implementation of that wire
 * protocol. We deliberately do NOT depend on `@canton-network/dapp-sdk`'s
 * `ExtensionAdapter`: its single bundled entry statically imports
 * `@walletconnect/sign-client` (an optional peer used only by its
 * WalletConnectAdapter), which is not installed and breaks every downstream
 * webpack/Next build that pulls `@partylayer/provider` into its graph
 * (confirmed against the live demo's `next build`). The protocol constants and
 * message shapes below mirror `@canton-network/core-types` (`WalletEvent`,
 * `SpliceMessage`) verbatim, so behaviour matches the official adapter.
 */

interface ExtensionChannelOptions {
  /** Routing key (announce `target`) included on every request message. */
  target?: string;
  /** Per-request timeout in ms. Default 30000. */
  timeoutMs?: number;
}
/**
 * Create a CIP-0103 provider that talks the splice-wallet postMessage protocol
 * over the page `window`, routed by `target`.
 */
declare function createExtensionChannelProvider(options?: ExtensionChannelOptions): CIP0103Provider;

/**
 * Async Wallet Handling
 *
 * CIP-0103 async wallet extensions allow methods like `connect` and
 * `prepareExecute` to return a `{ userUrl }` instead of completing
 * synchronously. The user must visit the URL (e.g., mobile wallet
 * approval screen), and the wallet provider emits an event when the
 * operation completes.
 *
 * This module provides helpers that abstract the wait-for-event pattern
 * so the Provider implementation can offer a unified surface to dApps.
 */

interface AsyncConnectOptions {
  /** Timeout for waiting for the async connect event (ms) */
  timeoutMs?: number;
  /** Callback when userUrl is available (for UI to redirect / show QR) */
  onUserUrl?: (url: string) => void;
}
interface AsyncPrepareExecuteOptions {
  timeoutMs?: number;
  onUserUrl?: (url: string) => void;
}
/**
 * Handle an async connect flow:
 *
 * 1. If connectResult is already isConnected (sync wallet), return immediately.
 * 2. If connectResult has userUrl, invoke onUserUrl callback for UI.
 * 3. Wait for 'connected' event from the wallet provider.
 * 4. Return the final ConnectResult.
 */
declare function handleAsyncConnect(
  walletProvider: CIP0103Provider,
  connectResult: CIP0103ConnectResult,
  options?: AsyncConnectOptions
): Promise<CIP0103ConnectResult>;
/**
 * Handle an async prepareExecute flow:
 *
 * 1. If result has userUrl, invoke onUserUrl callback for UI.
 * 2. Wait for 'txChanged' event with matching commandId.
 * 3. Return when txChanged reaches a terminal state (executed / failed).
 */
declare function handleAsyncPrepareExecute(
  walletProvider: CIP0103Provider,
  commandId: string,
  userUrl: string | undefined,
  options?: AsyncPrepareExecuteOptions
): Promise<CIP0103TxChangedEvent>;

/**
 * CIP-0103 Event Bus
 *
 * Minimal, spec-compliant event emitter.
 * - on() and removeListener() return the Provider (for chaining)
 * - emit() returns boolean (true if any listener was called)
 * - Listener errors are swallowed to prevent one handler from
 *   breaking others
 */

declare class CIP0103EventBus {
  private listeners;
  private owner;
  /** Set the owning Provider instance (for chaining returns) */
  setOwner(owner: CIP0103Provider): void;
  on<T = unknown>(event: string, listener: CIP0103EventListener<T>): CIP0103Provider;
  emit<T = unknown>(event: string, ...args: T[]): boolean;
  removeListener<T = unknown>(
    event: string,
    listenerToRemove: CIP0103EventListener<T>
  ): CIP0103Provider;
  /** Remove all listeners, optionally scoped to a single event */
  removeAllListeners(event?: string): void;
  /** Number of listeners for a given event */
  listenerCount(event: string): number;
}

/**
 * CIP-0103 Method Router
 *
 * Routes request({ method, params }) calls to the correct handler function.
 * By default, all 10 mandatory CIP-0103 methods are registered as passthrough
 * handlers that delegate to the native wallet Provider.
 *
 * Forward-compatible: unknown methods are passed through to the wallet provider
 * rather than rejected, allowing support for future CIP extensions.
 */

type MethodHandler<T = unknown> = (
  walletProvider: CIP0103Provider,
  params?: CIP0103RequestParams
) => Promise<T>;
declare class MethodRouter {
  private handlers;
  private walletProvider;
  constructor();
  /** Set / swap the underlying native wallet provider */
  setWalletProvider(provider: CIP0103Provider | null): void;
  /** Get the current wallet provider */
  getWalletProvider(): CIP0103Provider | null;
  /** Register (or override) a handler for a method name */
  register<T>(method: string, handler: MethodHandler<T>): void;
  /** Route a request to the appropriate handler */
  route<T>(payload: CIP0103RequestPayload): Promise<T>;
  /** Check whether a handler is registered for a given method */
  hasHandler(method: string): boolean;
  private registerDefaults;
}

export {
  type AnnounceDiscoveryOptions,
  type AnnouncedWallet,
  type AsyncConnectOptions,
  type AsyncPrepareExecuteOptions,
  type BridgeableClient,
  CIP0103EventBus,
  type DiscoveredProvider,
  type ExtensionChannelOptions,
  JSON_RPC_ERRORS,
  type MethodHandler,
  MethodRouter,
  PartyLayerProvider,
  type PartyLayerProviderOptions,
  ProviderRpcError,
  RPC_ERRORS,
  chainDisconnected,
  createExtensionChannelProvider,
  createProviderBridge,
  disconnected,
  discoverAnnouncedProviders,
  discoverInjectedProviders,
  discoverProviders,
  handleAsyncConnect,
  handleAsyncPrepareExecute,
  internalError,
  invalidParams,
  isCIP0103Provider,
  methodNotFound,
  resourceNotFound,
  resourceUnavailable,
  toPartyLayerError,
  toProviderRpcError,
  transactionRejected,
  unauthorized,
  unsupportedMethod,
  userRejected,
  waitForProvider,
};
