// API SURFACE SNAPSHOT — @partylayer/vue/pinia
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function definePartyLayerStore(store: SessionStore, id?: string): pinia.StoreDefinition<string, Pick<{ status: vue.ComputedRef<SessionStatus>; account: vue.ComputedRef<_partylayer_core.CIP0103Account | null>; accounts: vue.ComputedRef<readonly _partylayer_core.CIP0103Account[]>; networkId: vue.ComputedRef<string | null>; lastError: vue.ComputedRef<Error | null>; party: vue.ComputedRef<string | null>; isConnected: vue.ComputedRef<boolean>; isDisconnected: vue.ComputedRef<boolean>; connect: (params?: Record<string, unknown>) => Promise<SessionState>; disconnect: () => Promise<void>; restore: () => Promise<SessionState>; }, never>, Pick<{ status: vue.ComputedRef<SessionStatus>; account: vue.ComputedRef<_partylayer_core.CIP0103Account | null>; accounts: vue.ComputedRef<readonly _partylayer_core.CIP0103Account[]>; networkId: vue.ComputedRef<string | null>; lastError: vue.ComputedRef<Error | null>; party: vue.ComputedRef<string | null>; isConnected: vue.ComputedRef<boolean>; isDisconnected: vue.ComputedRef<boolean>; connect: (params?: Record<string, unknown>) => Promise<SessionState>; disconnect: () => Promise<void>; restore: () => Promise<SessionState>; }, "status" | "account" | "accounts" | "networkId" | "lastError" | "party" | "isConnected" | "isDisconnected">, Pick<{ status: vue.ComputedRef<SessionStatus>; account: vue.ComputedRef<_partylayer_core.CIP0103Account | null>; accounts: vue.ComputedRef<readonly _partylayer_core.CIP0103Account[]>; networkId: vue.ComputedRef<string | null>; lastError: vue.ComputedRef<Error | null>; party: vue.ComputedRef<string | null>; isConnected: vue.ComputedRef<boolean>; isDisconnected: vue.ComputedRef<boolean>; connect: (params?: Record<string, unknown>) => Promise<SessionState>; disconnect: () => Promise<void>; restore: () => Promise<SessionState>; }, "connect" | "disconnect" | "restore">>;
export { type PartyLayerStore, type PartyLayerStoreSurface, definePartyLayerStore };
import * as _partylayer_core from '@partylayer/core';
import * as pinia from 'pinia';
import * as vue from 'vue';
import { SessionStore, SessionStatus, SessionState, SessionAccount } from '@partylayer/session';
interface PartyLayerStoreSurface { status: SessionStatus; account: SessionAccount | null; accounts: readonly SessionAccount[]; networkId: string | null; lastError: Error | null; party: string | null; isConnected: boolean; isDisconnected: boolean; connect: (params?: Record<string, unknown>) => Promise<SessionState>; disconnect: () => Promise<void>; restore: () => Promise<SessionState>; }
type PartyLayerStore = ReturnType<ReturnType<typeof definePartyLayerStore>>;
