// API SURFACE SNAPSHOT — @partylayer/vue
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare const SESSION_STORE_KEY: InjectionKey<SessionStore | null>;
declare const partyLayerKeys: { readonly all: readonly [ "partylayer" ]; readonly connect: () => readonly [ "partylayer", "connect" ]; readonly disconnect: () => readonly [ "partylayer", "disconnect" ]; readonly signMessage: () => readonly [ "partylayer", "signMessage" ]; readonly submitTransaction: () => readonly [ "partylayer", "submitTransaction" ]; readonly account: () => readonly [ "partylayer", "account" ]; readonly session: () => readonly [ "partylayer", "session" ]; readonly wallets: (params?: { filter?: unknown; }) => readonly [ "partylayer", "wallets", { filter?: unknown; } ]; readonly registryStatus: () => readonly [ "partylayer", "registryStatus" ]; readonly transactionCostEstimate: (params?: { input?: unknown; }) => readonly [ "partylayer", "transactionCostEstimate", { input?: unknown; } ]; readonly paidTrafficCost: (params?: { input?: unknown; }) => readonly [ "partylayer", "paidTrafficCost", { input?: unknown; } ]; readonly damlContract: (params?: { key?: unknown; }) => readonly [ "partylayer", "damlContract", { key?: unknown; } ]; readonly exerciseChoice: () => readonly [ "partylayer", "exerciseChoice" ]; };
declare function createPartyLayerSession(config: ProvideSessionConfig): Plugin;
declare function injectSessionStore(): SessionStore | null;
declare function provideSessionStore(config: ProvideSessionConfig): SessionStore;
declare function useAccount(): UseAccountReturn;
declare function useAccountEffect(parameters?: UseAccountEffectParameters): void;
declare function useDamlContract<T>(parameters: UseDamlContractParameters<T>): UseDamlContractReturnType<T>;
declare function usePaidTrafficCost(parameters: UsePaidTrafficCostParameters): UsePaidTrafficCostReturnType;
declare function usePartyState(): UsePartyStateReturn;
declare function useSession(): UseSessionReturn;
declare function useTransactionCostEstimate(parameters: UseTransactionCostEstimateParameters): UseTransactionCostEstimateReturnType;
export { type PartyLayerKeys, type ProvideSessionConfig, SESSION_STORE_KEY, type SessionChain, type UseAccountEffectParameters, type UseAccountReturn, type UseDamlContractParameters, type UseDamlContractReturnType, type UsePaidTrafficCostParameters, type UsePaidTrafficCostReturnType, type UsePartyStateReturn, type UseSessionReturn, type UseTransactionCostEstimateParameters, type UseTransactionCostEstimateReturnType, createPartyLayerSession, injectSessionStore, partyLayerKeys, provideSessionStore, useAccount, useAccountEffect, useDamlContract, usePaidTrafficCost, usePartyState, useSession, useTransactionCostEstimate };
import { CIP0103Provider, PaidTrafficCost, CostEstimation } from '@partylayer/core';
import { InjectionKey, Plugin, ComputedRef, MaybeRefOrGetter } from 'vue';
import { SessionStore, SessionStoreOptions, SessionAccount, SessionStatus, SessionState, SessionEvent } from '@partylayer/session';
import { UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query';
interface SessionChain { id: string; }
interface UseAccountEffectParameters { onConnect?: (data: { account: SessionAccount | null; accounts: readonly SessionAccount[]; networkId: string | null; }) => void; onDisconnect?: () => void; onPartyChanged?: (data: { previous: string | null; current: string | null; }) => void; }
interface UseAccountReturn { party: ComputedRef<string | null>; address: ComputedRef<string | null>; account: ComputedRef<SessionAccount | null>; accounts: ComputedRef<readonly SessionAccount[]>; status: ComputedRef<SessionStatus>; isConnected: ComputedRef<boolean>; isConnecting: ComputedRef<boolean>; isReconnecting: ComputedRef<boolean>; isDisconnected: ComputedRef<boolean>; networkId: ComputedRef<string | null>; chain: ComputedRef<SessionChain | null>; lastError: ComputedRef<Error | null>; }
interface UseDamlContractParameters<T> { read: (signal?: AbortSignal) => Promise<T | null>; key?: MaybeRefOrGetter<unknown>; query?: Omit<UseQueryOptions<T | null, Error>, 'queryKey' | 'queryFn'>; }
interface UsePaidTrafficCostParameters { fetch: (signal?: AbortSignal) => Promise<PaidTrafficCost | null>; input?: MaybeRefOrGetter<unknown>; query?: Omit<UseQueryOptions<PaidTrafficCost | null, Error>, 'queryKey' | 'queryFn'>; }
interface UsePartyStateReturn { party: ComputedRef<string | null>; account: ComputedRef<SessionAccount | null>; accounts: ComputedRef<readonly SessionAccount[]>; status: ComputedRef<SessionStatus>; isConnected: ComputedRef<boolean>; isDisconnected: ComputedRef<boolean>; networkId: ComputedRef<string | null>; lastError: ComputedRef<Error | null>; }
interface UseSessionReturn { status: ComputedRef<SessionStatus>; account: ComputedRef<SessionAccount | null>; accounts: ComputedRef<readonly SessionAccount[]>; networkId: ComputedRef<string | null>; lastError: ComputedRef<Error | null>; isConnected: ComputedRef<boolean>; isConnecting: ComputedRef<boolean>; isReconnecting: ComputedRef<boolean>; isDisconnected: ComputedRef<boolean>; connect(params?: Record<string, unknown>): Promise<SessionState>; disconnect(): Promise<void>; restore(): Promise<SessionState>; on<T extends SessionEvent['type']>(event: T, handler: (event: Extract<SessionEvent, { type: T; }>) => void): () => void; }
interface UseTransactionCostEstimateParameters { estimate: (signal?: AbortSignal) => Promise<CostEstimation | null>; input?: MaybeRefOrGetter<unknown>; query?: Omit<UseQueryOptions<CostEstimation | null, Error>, 'queryKey' | 'queryFn'>; }
type PartyLayerKeys = typeof partyLayerKeys;
type ProvideSessionConfig = SessionStore | ({ provider: CIP0103Provider; } & Partial<SessionStoreOptions>);
type UseDamlContractReturnType<T> = UseQueryReturnType<T | null, Error> & { contract: ComputedRef<T | null | undefined>; };
type UsePaidTrafficCostReturnType = UseQueryReturnType<PaidTrafficCost | null, Error> & { paidTrafficCost: ComputedRef<PaidTrafficCost | null | undefined>; };
type UseTransactionCostEstimateReturnType = UseQueryReturnType<CostEstimation | null, Error> & { costEstimate: ComputedRef<CostEstimation | null | undefined>; };
