// API SURFACE SNAPSHOT — @partylayer/adapter-loop
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class LoopAdapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "5N Loop"; private currentProvider; getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, opts?: { timeoutMs?: number; partyId?: PartyId; }): Promise<AdapterConnectResult>; disconnect(_ctx: AdapterContext, _session: Session): Promise<void>; restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>; signMessage(ctx: AdapterContext, session: Session, params: SignMessageParams): Promise<SignedMessage>; signTransaction(_ctx: AdapterContext, _session: Session, _params: SignTransactionParams): Promise<SignedTransaction>; submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>; private isAcsRoute; private isSubmitRoute; private handleAcsQuery; private handleSubmitCommand; private templateIdHint; private mapNetworkToLoop; }
export { LoopAdapter };
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult } from '@partylayer/core';
