// API SURFACE SNAPSHOT — @partylayer/adapter-nightly
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class NightlyAdapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Nightly"; private wallet; getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, _opts?: { timeoutMs?: number; partyId?: PartyId; }): Promise<AdapterConnectResult>; disconnect(ctx: AdapterContext, _session: Session): Promise<void>; restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>; signMessage(ctx: AdapterContext, session: Session, params: SignMessageParams): Promise<SignedMessage>; signTransaction(_ctx: AdapterContext, _session: Session, _params: SignTransactionParams): Promise<SignedTransaction>; submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>; }
declare enum SignRequestResponseType { SIGN_REQUEST_APPROVED = "sign_request_approved", SIGN_REQUEST_REJECTED = "sign_request_rejected", SIGN_REQUEST_ERROR = "sign_request_error" }
export { NightlyAdapter };
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult } from '@partylayer/core';
interface CreateTransferCommandParams { receiverPartyId: string; amount: string; instrument: Instrument; memo?: string; expiryDate?: string; }
interface Instrument { id: string; admin: string; }
interface NightlyCantonProvider extends NightlyCantonWallet { connect: () => Promise<{ partyId: string; publicKey: string; }>; disconnect: () => Promise<void>; isConnected: () => boolean; }
interface NightlyCantonWallet { partyId: string; publicKey: string; signMessage: (message: string, onResponse: (response: SignRequestResponse) => void) => void; createTransferCommand: (params: CreateTransferCommandParams) => Promise<TransactionCommand>; submitTransactionCommand: (transactionCommand: TransactionCommand, onResponse: (response: SignRequestResponse) => void) => void; getPendingTransactions: () => Promise<unknown[] | null>; getHoldingUtxos: () => Promise<unknown[] | null>; }
interface SignRequestResponse { type: SignRequestResponseType; data: { signature?: string; updateId?: string; } | { reason: string; } | { error: string; }; }
interface TransactionCommand { command: unknown; disclosedContracts: unknown[]; }
interface Window { nightly?: { canton?: NightlyCantonProvider; }; }
