// API SURFACE SNAPSHOT — @partylayer/react/query
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare const partyLayerKeys: { readonly all: readonly [ "partylayer" ]; readonly connect: () => readonly [ "partylayer", "connect" ]; readonly disconnect: () => readonly [ "partylayer", "disconnect" ]; readonly signMessage: () => readonly [ "partylayer", "signMessage" ]; readonly submitTransaction: () => readonly [ "partylayer", "submitTransaction" ]; readonly account: () => readonly [ "partylayer", "account" ]; readonly session: () => readonly [ "partylayer", "session" ]; readonly wallets: (params?: { filter?: unknown; }) => readonly [ "partylayer", "wallets", { filter?: unknown; } ]; readonly registryStatus: () => readonly [ "partylayer", "registryStatus" ]; readonly transactionCostEstimate: (params?: { input?: unknown; }) => readonly [ "partylayer", "transactionCostEstimate", { input?: unknown; } ]; readonly paidTrafficCost: (params?: { input?: unknown; }) => readonly [ "partylayer", "paidTrafficCost", { input?: unknown; } ]; readonly damlContract: (params?: { key?: unknown; }) => readonly [ "partylayer", "damlContract", { key?: unknown; } ]; readonly tokenHoldings: (params?: { key?: unknown; }) => readonly [ "partylayer", "tokenHoldings", { key?: unknown; } ]; readonly tokenAllocations: (params?: { key?: unknown; }) => readonly [ "partylayer", "tokenAllocations", { key?: unknown; } ]; readonly exerciseChoice: () => readonly [ "partylayer", "exerciseChoice" ]; readonly transferInstruction: () => readonly [ "partylayer", "transferInstruction" ]; };
declare function optimisticMutationOptions<TQueryData, TVariables = unknown>(config: OptimisticMutationConfig<TQueryData, TVariables>): Pick<UseMutationOptions<unknown, Error, TVariables>, 'onMutate' | 'onError' | 'onSettled'>;
declare function useChoice<R, V>(parameters: UseChoiceParameters<R, V>): UseChoiceReturnType<R, V>;
declare function useConnect(parameters?: UseConnectParameters): UseConnectReturnType;
declare function useDamlContract<T>(parameters: UseDamlContractParameters<T>): UseDamlContractReturnType<T>;
declare function useDisconnect(parameters?: UseDisconnectParameters): UseDisconnectReturnType;
declare function usePaidTrafficCost(parameters: UsePaidTrafficCostParameters): UsePaidTrafficCostReturnType;
declare function useSignMessage(parameters?: UseSignMessageParameters): UseSignMessageReturnType;
declare function useSubmitTransaction(parameters?: UseSubmitTransactionParameters): UseSubmitTransactionReturnType;
declare function useSuspensePaidTrafficCost(parameters: UseSuspensePaidTrafficCostParameters): UseSuspensePaidTrafficCostReturnType;
declare function useSuspenseTransactionCostEstimate(parameters: UseSuspenseTransactionCostEstimateParameters): UseSuspenseTransactionCostEstimateReturnType;
declare function useSuspenseWallets(parameters?: UseSuspenseWalletsParameters): UseSuspenseWalletsReturnType;
declare function useTokenAllocations(parameters: UseTokenAllocationsParameters): UseTokenAllocationsReturnType;
declare function useTokenHoldings(parameters: UseTokenHoldingsParameters): UseTokenHoldingsReturnType;
declare function useTransactionCostEstimate(parameters: UseTransactionCostEstimateParameters): UseTransactionCostEstimateReturnType;
declare function useTransferInstruction<R = unknown>(parameters: UseTransferInstructionParameters<R>): UseTransferInstructionReturnType<R>;
declare function useWallets(parameters?: UseWalletsParameters): UseWalletsReturnType;
export { CostEstimation, PaidTrafficCost, TrafficCost } from '@partylayer/core';
export { type ConnectVariables, type DisconnectVariables, type OptimisticContext, type OptimisticMutationConfig, type PartyLayerKeys, type TokenAllocation, type TokenAllocationSpecification, type TokenHolding, type TokenInstrumentId, type TokenLock, type TokenSettlementInfo, type TokenSettlementReference, type TokenTransfer, type TokenTransferLeg, type TransferInstructionStatus, type UseChoiceParameters, type UseChoiceReturnType, type UseConnectParameters, type UseConnectReturnType, type UseDamlContractParameters, type UseDamlContractReturnType, type UseDisconnectParameters, type UseDisconnectReturnType, type UsePaidTrafficCostParameters, type UsePaidTrafficCostReturnType, type UseSignMessageParameters, type UseSignMessageReturnType, type UseSubmitTransactionParameters, type UseSubmitTransactionReturnType, type UseSuspensePaidTrafficCostParameters, type UseSuspensePaidTrafficCostReturnType, type UseSuspenseTransactionCostEstimateParameters, type UseSuspenseTransactionCostEstimateReturnType, type UseSuspenseWalletsParameters, type UseSuspenseWalletsReturnType, type UseTokenAllocationsParameters, type UseTokenAllocationsReturnType, type UseTokenHoldingsParameters, type UseTokenHoldingsReturnType, type UseTransactionCostEstimateParameters, type UseTransactionCostEstimateReturnType, type UseTransferInstructionParameters, type UseTransferInstructionReturnType, type UseWalletsParameters, type UseWalletsReturnType, optimisticMutationOptions, partyLayerKeys, useChoice, useConnect, useDamlContract, useDisconnect, usePaidTrafficCost, useSignMessage, useSubmitTransaction, useSuspensePaidTrafficCost, useSuspenseTransactionCostEstimate, useSuspenseWallets, useTokenAllocations, useTokenHoldings, useTransactionCostEstimate, useTransferInstruction, useWallets };
import { ConnectOptions, Session, WalletFilter, WalletInfo, SignedMessage, SignMessageParams, TxReceipt, SubmitTransactionParams } from '@partylayer/sdk';
import { CostEstimation, PaidTrafficCost } from '@partylayer/core';
import { UseMutationOptions, UseMutationResult, UseQueryOptions, UseQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult, QueryClient, QueryKey } from '@tanstack/react-query';
interface OptimisticContext<TQueryData> { previous: TQueryData | undefined; }
interface OptimisticMutationConfig<TQueryData, TVariables> { queryClient: QueryClient; queryKey: QueryKey; update: (previous: TQueryData | undefined, variables: TVariables) => TQueryData; invalidate?: boolean; }
interface TokenAllocation { allocation: TokenAllocationSpecification; holdingCids: string[]; meta?: Record<string, string>; }
interface TokenAllocationSpecification { settlement: TokenSettlementInfo; transferLegId: string; transferLeg: TokenTransferLeg; }
interface TokenHolding { owner: string; instrumentId: TokenInstrumentId; amount: string; lock?: TokenLock; meta?: Record<string, string>; }
interface TokenInstrumentId { admin: string; id: string; }
interface TokenLock { holders: string[]; expiresAt?: string; expiresAfter?: string; context?: string; }
interface TokenSettlementInfo { executor: string; settlementRef: TokenSettlementReference; requestedAt: string; allocateBefore: string; settleBefore: string; meta?: Record<string, string>; }
interface TokenSettlementReference { id: string; cid?: string; }
interface TokenTransfer { sender: string; receiver: string; amount: string; instrumentId: TokenInstrumentId; lock?: TokenLock; requestedAt: string; executeBefore: string; inputHoldingCids: string[]; meta?: Record<string, string>; }
interface TokenTransferLeg { sender: string; receiver: string; amount: string; instrumentId: TokenInstrumentId; meta?: Record<string, string>; }
interface UseChoiceParameters<R, V> { exercise: (variables: V, signal?: AbortSignal) => Promise<R>; mutation?: Omit<UseMutationOptions<R, Error, V>, 'mutationFn' | 'mutationKey'>; }
interface UseConnectParameters { mutation?: Omit<UseMutationOptions<Session, Error, ConnectVariables>, 'mutationFn' | 'mutationKey'>; }
interface UseDamlContractParameters<T> { read: (signal?: AbortSignal) => Promise<T | null>; key?: unknown; query?: Omit<UseQueryOptions<T | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseDisconnectParameters { mutation?: Omit<UseMutationOptions<void, Error, DisconnectVariables>, 'mutationFn' | 'mutationKey'>; }
interface UsePaidTrafficCostParameters { fetch: (signal?: AbortSignal) => Promise<PaidTrafficCost | null>; input?: unknown; query?: Omit<UseQueryOptions<PaidTrafficCost | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseSignMessageParameters { mutation?: Omit<UseMutationOptions<SignedMessage, Error, SignMessageParams>, 'mutationFn' | 'mutationKey'>; }
interface UseSubmitTransactionParameters { mutation?: Omit<UseMutationOptions<TxReceipt, Error, SubmitTransactionParams>, 'mutationFn' | 'mutationKey'>; }
interface UseSuspensePaidTrafficCostParameters { fetch: (signal?: AbortSignal) => Promise<PaidTrafficCost | null>; input?: unknown; query?: Omit<UseSuspenseQueryOptions<PaidTrafficCost | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseSuspenseTransactionCostEstimateParameters { estimate: (signal?: AbortSignal) => Promise<CostEstimation | null>; input?: unknown; query?: Omit<UseSuspenseQueryOptions<CostEstimation | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseSuspenseWalletsParameters { filter?: WalletFilter; query?: Omit<UseSuspenseQueryOptions<WalletInfo[], Error>, 'queryKey' | 'queryFn'>; }
interface UseTokenAllocationsParameters { read: (signal?: AbortSignal) => Promise<TokenAllocation[] | null>; key?: unknown; query?: Omit<UseQueryOptions<TokenAllocation[] | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseTokenHoldingsParameters { read: (signal?: AbortSignal) => Promise<TokenHolding[] | null>; key?: unknown; query?: Omit<UseQueryOptions<TokenHolding[] | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseTransactionCostEstimateParameters { estimate: (signal?: AbortSignal) => Promise<CostEstimation | null>; input?: unknown; query?: Omit<UseQueryOptions<CostEstimation | null, Error>, 'queryKey' | 'queryFn'>; }
interface UseTransferInstructionParameters<R = unknown> { submit: (transfer: TokenTransfer, signal?: AbortSignal) => Promise<R>; mutation?: Omit<UseMutationOptions<R, Error, TokenTransfer>, 'mutationFn' | 'mutationKey'>; }
interface UseWalletsParameters { filter?: WalletFilter; query?: Omit<UseQueryOptions<WalletInfo[], Error>, 'queryKey' | 'queryFn'>; }
type ConnectVariables = ConnectOptions | undefined;
type DisconnectVariables = void;
type PartyLayerKeys = typeof partyLayerKeys;
type TransferInstructionStatus = 'pending' | 'completed' | 'failed';
type UseChoiceReturnType<R, V> = UseMutationResult<R, Error, V> & { exerciseChoice: UseMutationResult<R, Error, V>['mutate']; exerciseChoiceAsync: UseMutationResult<R, Error, V>['mutateAsync']; };
type UseConnectReturnType = UseMutationResult<Session, Error, ConnectVariables> & { connect: UseMutationResult<Session, Error, ConnectVariables>['mutate']; connectAsync: UseMutationResult<Session, Error, ConnectVariables>['mutateAsync']; };
type UseDamlContractReturnType<T> = UseQueryResult<T | null, Error> & { contract: T | null | undefined; };
type UseDisconnectReturnType = UseMutationResult<void, Error, DisconnectVariables> & { disconnect: UseMutationResult<void, Error, DisconnectVariables>['mutate']; disconnectAsync: UseMutationResult<void, Error, DisconnectVariables>['mutateAsync']; };
type UsePaidTrafficCostReturnType = UseQueryResult<PaidTrafficCost | null, Error> & { paidTrafficCost: PaidTrafficCost | null | undefined; };
type UseSignMessageReturnType = UseMutationResult<SignedMessage, Error, SignMessageParams> & { signMessage: UseMutationResult<SignedMessage, Error, SignMessageParams>['mutate']; signMessageAsync: UseMutationResult<SignedMessage, Error, SignMessageParams>['mutateAsync']; };
type UseSubmitTransactionReturnType = UseMutationResult<TxReceipt, Error, SubmitTransactionParams> & { submitTransaction: UseMutationResult<TxReceipt, Error, SubmitTransactionParams>['mutate']; submitTransactionAsync: UseMutationResult<TxReceipt, Error, SubmitTransactionParams>['mutateAsync']; };
type UseSuspensePaidTrafficCostReturnType = UseSuspenseQueryResult<PaidTrafficCost | null, Error> & { paidTrafficCost: PaidTrafficCost | null; };
type UseSuspenseTransactionCostEstimateReturnType = UseSuspenseQueryResult<CostEstimation | null, Error> & { costEstimate: CostEstimation | null; };
type UseSuspenseWalletsReturnType = UseSuspenseQueryResult<WalletInfo[], Error> & { wallets: UseSuspenseQueryResult<WalletInfo[], Error>['data']; };
type UseTokenAllocationsReturnType = UseQueryResult<TokenAllocation[] | null, Error> & { allocations: TokenAllocation[] | null | undefined; };
type UseTokenHoldingsReturnType = UseQueryResult<TokenHolding[] | null, Error> & { holdings: TokenHolding[] | null | undefined; };
type UseTransactionCostEstimateReturnType = UseQueryResult<CostEstimation | null, Error> & { costEstimate: CostEstimation | null | undefined; };
type UseTransferInstructionReturnType<R = unknown> = UseMutationResult<R, Error, TokenTransfer> & { submitTransfer: UseMutationResult<R, Error, TokenTransfer>['mutate']; submitTransferAsync: UseMutationResult<R, Error, TokenTransfer>['mutateAsync']; };
type UseWalletsReturnType = UseQueryResult<WalletInfo[], Error> & { wallets: UseQueryResult<WalletInfo[], Error>['data']; };
