// API SURFACE SNAPSHOT — @partylayer/testing/query
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function createQueryHarness(config?: { wallet?: MockWalletConfig; session?: Partial<SessionStoreOptions>; query?: QueryClientConfig; }): QueryHarness;
declare function createTestQueryClient(overrides?: QueryClientConfig): QueryClient;
declare function expectInvalidated(client: QueryClient, key: QueryKey): boolean;
declare function getQueryState<T>(client: QueryClient, key: QueryKey): QueryStateView<T>;
declare function trackOptimisticRollback<T>(client: QueryClient, key: QueryKey): OptimisticRollback<T>;
export { type OptimisticRollback, type QueryHarness, type QueryStateView, createQueryHarness, createTestQueryClient, expectInvalidated, getQueryState, trackOptimisticRollback };
import '@partylayer/core';
import '@partylayer/provider';
import { O as OfflineHarness, e as MockWalletConfig } from './offline-CELeTEq9.js';
import { QueryClient, QueryClientConfig, QueryKey } from '@tanstack/query-core';
import { SessionStoreOptions } from '@partylayer/session';
interface OptimisticRollback<T> { readonly snapshot: T | undefined; apply(next: T): void; rollback(): void; current(): T | undefined; }
interface QueryHarness extends OfflineHarness { readonly queryClient: QueryClient; }
interface QueryStateView<T> { readonly data: T | undefined; readonly status: 'pending' | 'error' | 'success'; readonly fetchStatus: 'fetching' | 'paused' | 'idle'; readonly isInvalidated: boolean; }
