// API SURFACE SNAPSHOT — @partylayer/adapter-walletconnect
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import {
  WalletAdapter,
  CapabilityKey,
  AdapterDetectResult,
  AdapterContext,
  PartyId,
  AdapterConnectResult,
  Session,
  PersistedSession,
  SignTransactionParams,
  SignedTransaction,
  SubmitTransactionParams,
  TxReceipt,
  AdapterEventName,
} from '@partylayer/core';

/** SIWX (Sign-In-With-Canton) params, forwarded verbatim to the official adapter. */
interface SignInWithCantonParams {
  domain: string;
  uri: string;
  version: string;
  statement?: string;
  nonce?: string;
  requestId?: string;
  notBefore?: string;
  issuedAt?: string;
  expirationTime?: string;
  resources?: string[];
}
interface WalletConnectAdapterConfig {
  /** WalletConnect Cloud project id (required). */
  projectId: string;
  /** dApp metadata shown to the wallet during pairing. */
  metadata?: {
    name: string;
    description: string;
    url: string;
    icons: string[];
  };
  /**
   * Called with the WalletConnect pairing URI. Wire this to the connect modal's
   * QR UI (mirrors how adapter-loop surfaces its pairing QR). The official
   * adapter fires it once the session proposal is created.
   */
  onUri?: (uri: string) => void;
  /** Optional SIWX request triggered after the session is established. */
  signInWithCanton?: SignInWithCantonParams;
  /** Callback for the SIWX result. */
  onSignInWithCanton?: (result: unknown) => void;
  /**
   * Optional CAIP-2 chain id. Left UNSET by default per the Canton WC spec —
   * request the `canton` namespace and use whatever network the wallet provides.
   */
  chainId?: string;
}
/**
 * Structural view of the official adapter we drive. Declared locally (NOT
 * imported from `@canton-network/dapp-sdk`) so this module references no
 * dapp-sdk types and stays free of any static dapp-sdk import.
 */
interface OfficialWcAdapter {
  request<T = unknown>(args: { method: string; params?: unknown }): Promise<T>;
  on(event: string, listener: (...args: unknown[]) => void): unknown;
  removeListener(event: string, listener: (...args: unknown[]) => void): unknown;
  teardown(): void;
  restore(): Promise<unknown>;
  detect(): Promise<boolean>;
}
type OfficialWcFactory = (
  config: Record<string, unknown>
) => OfficialWcAdapter | Promise<OfficialWcAdapter>;
interface WalletConnectAdapterOptions {
  /**
   * Test seam: supply the official adapter instead of dynamically importing
   * `@canton-network/dapp-sdk`. Defaults to the real dynamic import.
   */
  createOfficialAdapter?: OfficialWcFactory;
}
declare class WalletConnectAdapter implements WalletAdapter {
  readonly walletId: _partylayer_core.WalletId;
  readonly name = 'WalletConnect';
  private readonly config;
  private readonly createOfficial;
  private official;
  constructor(config: WalletConnectAdapterConfig, options?: WalletConnectAdapterOptions);
  getCapabilities(): CapabilityKey[];
  /**
   * WalletConnect is an always-available connection METHOD (not extension-gated)
   * when a `projectId` is configured. Pure (no dynamic import) so rendering the
   * picker never pulls dapp-sdk.
   */
  detectInstalled(): Promise<AdapterDetectResult>;
  /** WalletInfo-ish metadata for pickers that surface adapters directly. */
  getInfo(): {
    id: string;
    name: string;
    icon: string;
  };
  private buildOfficialConfig;
  private ensureOfficial;
  connect(
    ctx: AdapterContext,
    _opts?: {
      timeoutMs?: number;
      partyId?: PartyId;
      preferInstalled?: boolean;
    }
  ): Promise<AdapterConnectResult>;
  disconnect(ctx: AdapterContext, _session: Session): Promise<void>;
  restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>;
  signTransaction(
    _ctx: AdapterContext,
    _session: Session,
    _params: SignTransactionParams
  ): Promise<SignedTransaction>;
  submitTransaction(
    _ctx: AdapterContext,
    session: Session,
    params: SubmitTransactionParams
  ): Promise<TxReceipt>;
  /**
   * Subscribe to adapter events by delegating to the official adapter's event
   * bus (events arrive via `session_event` and are buffered until a listener
   * attaches, so a late subscriber still receives them). Returns an unsubscribe.
   */
  on(event: AdapterEventName, handler: (payload: unknown) => void): () => void;
}

export {
  type SignInWithCantonParams,
  WalletConnectAdapter,
  type WalletConnectAdapterConfig,
  type WalletConnectAdapterOptions,
};
