// API SURFACE SNAPSHOT — @partylayer/session
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare const CURRENT_SESSION_ENVELOPE_VERSION: 1;
declare const DEFAULT_RETRY_POLICY: RetryPolicy;
declare const defaultChannelFactory: ChannelFactory;
declare function computeBackoffDelay(policy: RetryPolicy, attempt: number, rand?: () => number): number;
declare function createEncryptedIndexedDBStorage(options?: EncryptedStorageOptions): SessionStorage;
declare function createEncryptedLocalStorage(options?: EncryptedStorageOptions): SessionStorage;
declare function createMemoryStorage(): SessionStorage;
declare function createSessionStore(provider: CIP0103Provider, options?: SessionStoreOptions): SessionStore;
declare function decodeSessionEnvelope(plaintext: string): PersistedSessionSnapshot | null;
declare function encodeSessionEnvelope(snapshot: PersistedSessionSnapshot): string;
declare function migrateSessionEnvelope(parsed: unknown): PersistedSessionSnapshot | null;
declare function openSyncChannel(storageKey: string, options?: BroadcastOptions, explicitOrigin?: string): SyncChannel;
declare function reconcileSession(snapshot: PersistedSessionSnapshot, live: LiveSessionStatus): ReconcileResult;
declare function restoreSession(storage: SessionStorage, key: string, now?: number): Promise<PersistedSessionSnapshot | null>;
export { type BroadcastChannelLike, type BroadcastEnvelope, type BroadcastOptions, CURRENT_SESSION_ENVELOPE_VERSION, type ChannelFactory, DEFAULT_RETRY_POLICY, type EncryptedStorageOptions, type ExpiryOptions, type InvalidationEvent, type LiveSessionStatus, type MaybePromise, type PersistedSessionSnapshot, type ReauthContext, type ReconcileResult, type RetryPolicy, type SessionAccount, type SessionDiff, type SessionEvent, type SessionState, type SessionStatus, type SessionStorage, type SessionStore, type SessionStoreOptions, type SyncChannel, computeBackoffDelay, createEncryptedIndexedDBStorage, createEncryptedLocalStorage, createMemoryStorage, createSessionStore, decodeSessionEnvelope, defaultChannelFactory, encodeSessionEnvelope, migrateSessionEnvelope, openSyncChannel, reconcileSession, restoreSession };
import { CIP0103Account, CIP0103Provider } from '@partylayer/core';
interface BroadcastChannelLike { postMessage(data: unknown): void; close(): void; onmessage: ((ev: { data: unknown; }) => void) | null; }
interface BroadcastEnvelope { readonly v: 1; readonly kind: 'disconnect' | 'party' | 'network'; readonly partyId?: string | null; readonly networkId?: string | null; }
interface BroadcastOptions { channelFactory?: ChannelFactory; }
interface EncryptedStorageOptions { origin?: string; }
interface ExpiryOptions { ttlMs?: number; onReauthRequired?: (ctx: ReauthContext) => Promise<void> | void; pendingQueueSize?: number; }
interface InvalidationEvent { readonly type: 'party:changed' | 'network:changed'; readonly previous: string | null; readonly current: string | null; }
interface LiveSessionStatus { readonly account: SessionAccount | null; readonly networkId: string | null; }
interface PersistedSessionSnapshot { readonly account: SessionAccount | null; readonly accounts: readonly SessionAccount[]; readonly networkId: string | null; readonly connectedAt: number; readonly expiresAt?: number; }
interface ReauthContext { readonly reason: 'expired'; readonly expiredAt: number; }
interface ReconcileResult { readonly matches: boolean; readonly diffs: readonly SessionDiff[]; }
interface RetryPolicy { baseDelayMs: number; factor: number; maxDelayMs: number; maxAttempts: number; jitter?: boolean; }
interface SessionDiff { readonly field: 'account' | 'networkId'; readonly persisted: string | null; readonly live: string | null; }
interface SessionState { readonly status: SessionStatus; readonly account: SessionAccount | null; readonly accounts: readonly SessionAccount[]; readonly networkId: string | null; readonly lastError: Error | null; }
interface SessionStorage { getItem(key: string): MaybePromise<string | null>; setItem(key: string, value: string): MaybePromise<void>; removeItem(key: string): MaybePromise<void>; }
interface SessionStore { getSnapshot(): SessionState; subscribe(listener: () => void): () => void; connect(params?: Record<string, unknown>): Promise<SessionState>; disconnect(): Promise<void>; restore(): Promise<SessionState>; init(): Promise<SessionState>; getProvider(): CIP0103Provider; on(event: SessionEvent['type'], handler: (event: SessionEvent) => void): () => void; enqueue<T>(op: () => Promise<T>): Promise<T>; destroy(): void; }
interface SessionStoreOptions { storage?: SessionStorage; storageKey?: string; reconnect?: RetryPolicy | false; expiry?: ExpiryOptions; broadcast?: boolean | BroadcastOptions; persistSnapshot?: boolean; onInvalidate?: (event: InvalidationEvent) => void | Promise<void>; }
interface SyncChannel { readonly active: boolean; post(env: BroadcastEnvelope): void; onMessage(handler: (env: BroadcastEnvelope) => void): void; close(): void; }
type ChannelFactory = (name: string) => BroadcastChannelLike | null;
type MaybePromise<T> = T | Promise<T>;
type SessionAccount = CIP0103Account;
type SessionEvent = { readonly type: 'reconnect:scheduled'; readonly attempt: number; readonly delayMs: number; } | { readonly type: 'reconnect:attempt'; readonly attempt: number; } | { readonly type: 'reconnect:succeeded'; readonly attempt: number; } | { readonly type: 'reconnect:gaveup'; readonly attempts: number; readonly lastError: Error | null; } | { readonly type: 'session:expired'; readonly expiredAt: number; } | { readonly type: 'party:changed'; readonly previous: string | null; readonly current: string | null; } | { readonly type: 'network:changed'; readonly previous: string | null; readonly current: string | null; };
type SessionStatus = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';
