// API SURFACE SNAPSHOT — @partylayer/adapter-console
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class ConsoleAdapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Console Wallet"; private readonly target; private activeTransport; constructor(config?: ConsoleAdapterConfig); getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, _opts?: { timeoutMs?: number; partyId?: PartyId; preferInstalled?: boolean; }): Promise<AdapterConnectResult>; disconnect(ctx: AdapterContext, session: Session): Promise<void>; restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>; signMessage(ctx: AdapterContext, session: Session, params: SignMessageParams): Promise<SignedMessage>; signTransaction(ctx: AdapterContext, session: Session, params: SignTransactionParams): Promise<SignedTransaction>; submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>; on(event: 'connect' | 'disconnect' | 'sessionExpired' | 'txStatus' | 'error', handler: (payload: unknown) => void): () => void; private detectExtension; }
export { ConsoleAdapter, type ConsoleAdapterConfig, type ConsoleConnectionTarget };
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult } from '@partylayer/core';
interface ConsoleAdapterConfig { target?: ConsoleConnectionTarget; }
type ConsoleConnectionTarget = 'local' | 'remote' | 'combined';
