// API SURFACE SNAPSHOT — @partylayer/registry-client
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import {
  NetworkId,
  AdapterTransport,
  ProviderDetection,
  Cip0103Support,
  WalletInfo,
  PartyLayerError,
} from '@partylayer/core';
export {
  Cip0103StatusForDetection,
  Cip0103Support,
  ProviderDetection,
  ProviderMatcher,
  WalletInfo,
  deriveGenericWalletName,
  findMatchingWallet,
  findMatchingWalletInfo,
  isCip0103Native,
  matchesProviderDetection,
} from '@partylayer/core';

/**
 * Wallet Registry Schema v1
 *
 * This schema defines the structure of the wallet registry JSON.
 * The registry is versioned and supports:
 * - Multiple wallet entries
 * - Versioning and rollback
 * - Integrity checks (Ed25519 signatures)
 * - Multi-channel (stable/beta)
 * - Forward compatibility
 *
 * References:
 * - Wallet Integration Guide: https://docs.digitalasset.com/integrate/devnet/index.html
 */

/**
 * Registry schema version
 */
declare const REGISTRY_SCHEMA_VERSION = '1.0.0';
/**
 * Registry channel
 */
type RegistryChannel = 'stable' | 'beta';
/**
 * Wallet entry in registry
 */
interface RegistryWalletEntry {
  /** Wallet identifier (must be unique within channel) */
  id: string;
  /** Display name */
  name: string;
  /** Short description */
  description?: string;
  /** Homepage URL */
  homepage?: string;
  /** Icon URL (should be absolute) */
  icon?: string;
  /** Supported networks */
  supportedNetworks: NetworkId[];
  /** Wallet capabilities */
  capabilities: {
    signMessage: boolean;
    signTransaction: boolean;
    submitTransaction: boolean;
    transactionStatus: boolean;
    switchNetwork: boolean;
    multiParty: boolean;
    mobileConnect?: boolean;
    remoteSigner?: boolean;
  };
  /** Adapter configuration */
  adapter: {
    /** Adapter type/name */
    type: string;
    /**
     * How the SDK obtains this wallet's provider. Optional + additive — when
     * omitted the SDK uses today's behavior (injected `window.canton` scan /
     * announce). `'discovery-adapter'` routes the entry through the generic
     * official-adapter bridge: the SDK matches an app-supplied
     * `OfficialProviderAdapter` whose `providerId` equals `config.providerId`.
     * No wallet-specific adapter package is involved.
     */
    transport?: AdapterTransport;
    /**
     * Adapter-specific configuration. For `transport: 'discovery-adapter'`,
     * `config.providerId` (string) keys the app-supplied official adapter.
     */
    config?: Record<string, unknown>;
  };
  /** Installation detection hints */
  installation?: {
    /** Check if wallet is installed via window property */
    windowProperty?: string;
    /** Check if wallet is installed via script tag */
    scriptTag?: string;
    /** Check if wallet is installed via browser extension */
    extensionId?: string;
    /** Deep link URL for mobile wallet connect */
    deeplink?: string;
    /** OAuth-based authentication */
    oauth?: boolean;
  };
  /** SDK version compatibility */
  sdkVersion?: string;
  /** Metadata version (for cache invalidation) */
  version?: string;
  /** Origin allowlist (optional - if present, only these origins can connect) */
  originAllowlist?: string[];
  /**
   * Marks the entry as beta even when it ships in the `stable` registry
   * channel. UIs (modal, picker, capability matrix) can use this flag to
   * surface a "Beta" badge regardless of which channel file the entry
   * lives in. Optional and additive — older registries omit it and the
   * flag defaults to `false`.
   */
  beta?: boolean;
  /**
   * Optional CIP-0103 runtime detection rules. When present, the SDK +
   * picker can match the currently-injected `window.canton` provider to
   * this entry and surface it in the "CIP-0103 Native" section with full
   * branding. Lets us add new CIP-0103 wallets to the ecosystem with a
   * registry JSON update — no SDK code change required.
   */
  providerDetection?: ProviderDetection;
  /**
   * Canonical CIP-0103 support marker. When `cip0103.native === true`
   * the picker always renders this entry in the "CIP-0103 NATIVE"
   * section, regardless of install state. The accompanying `evidence`
   * field is intended to be a public URL that justifies the claim
   * (npm package readme, blog post, etc.) and may be surfaced by UIs as
   * a tooltip / "verified" link.
   */
  cip0103?: Cip0103Support;
}
/**
 * Registry metadata
 */
interface RegistryMetadata {
  /** Registry version (semver) */
  registryVersion: string;
  /** Schema version */
  schemaVersion: string;
  /** ISO 8601 timestamp when registry was published */
  publishedAt: string;
  /** Channel (stable or beta) */
  channel: RegistryChannel;
  /** Monotonic sequence number (increments on each update) */
  sequence: number;
  /** Registry publisher */
  publisher?: string;
}
/**
 * Wallet Registry v1 structure
 *
 * Note: Signature is NOT embedded. It's in a separate .sig file.
 */
interface WalletRegistryV1 {
  /** Registry metadata */
  metadata: RegistryMetadata;
  /** Array of wallet entries */
  wallets: RegistryWalletEntry[];
}
/**
 * Registry signature file format
 *
 * This is stored separately as registry.sig
 */
interface RegistrySignature {
  /** Signature algorithm (always 'ed25519') */
  algorithm: 'ed25519';
  /** Signature value (base64-encoded) */
  signature: string;
  /** Public key fingerprint (for key identification) */
  keyFingerprint: string;
  /** Timestamp when signed */
  signedAt: string;
}
/**
 * Validate registry structure
 */
declare function validateRegistry(registry: unknown): registry is WalletRegistryV1;
/**
 * Validate wallet entry
 */
declare function validateWalletEntry(entry: unknown): entry is RegistryWalletEntry;
/**
 * Convert registry entry to wallet info
 */
declare function registryEntryToWalletInfo(
  entry: RegistryWalletEntry,
  channel: RegistryChannel
): WalletInfo;
/**
 * @deprecated Use registryEntryToWalletInfo instead
 */
declare function registryEntryToMetadata(entry: RegistryWalletEntry): WalletInfo;

/**
 * Registry status information
 */
interface RegistryStatus {
  /** Source of registry data */
  source: 'network' | 'cache';
  /** Whether signature was verified */
  verified: boolean;
  /** Registry channel */
  channel: RegistryChannel;
  /** Sequence number */
  sequence: number;
  /** Whether registry is stale (past TTL) */
  stale: boolean;
  /** When registry was fetched */
  fetchedAt: number;
  /** ETag from last successful fetch */
  etag?: string;
  /** Error if verification/fetch failed */
  error?: PartyLayerError;
}
/**
 * Cached registry snapshot
 */
interface CachedRegistry {
  /** Registry data */
  registry: WalletRegistryV1;
  /** Whether signature was verified */
  verified: boolean;
  /** When fetched */
  fetchedAt: number;
  /** ETag */
  etag?: string;
  /** Sequence number */
  sequence: number;
}
/**
 * Last fetch attempt info
 */
interface LastFetchAttempt {
  /** When attempted */
  fetchedAt: number;
  /** Error code if failed */
  errorCode?: string;
}

/**
 * Registry client for fetching and caching wallet registry
 *
 * Features:
 * - Ed25519 signature verification
 * - Multi-channel support (stable/beta)
 * - Sequence number validation (prevents downgrades)
 * - Last-known-good caching
 * - SWR pattern (serve cached immediately, refresh in background)
 * - ETag support for efficient updates
 *
 * References:
 * - Wallet Integration Guide: https://docs.digitalasset.com/integrate/devnet/index.html
 */

/**
 * Registry client options
 */
interface RegistryClientOptions {
  /** Base registry URL (client appends /v1/{channel}/registry.json) */
  registryUrl?: string;
  /** Registry channel */
  channel?: RegistryChannel;
  /** Public keys for signature verification (base64) */
  registryPublicKeys?: string[];
  /** Cache TTL in milliseconds (default: 1 hour) */
  cacheTtl?: number;
  /** Stale TTL in milliseconds (default: 24 hours - cache usable but marked stale) */
  staleTtl?: number;
  /** Enable cache (default: true) */
  enableCache?: boolean;
  /** Custom fetch function */
  fetch?: typeof fetch;
  /** Fetch timeout in milliseconds (default: 8000) */
  fetchTimeout?: number;
  /** Storage adapter for persistent cache */
  storage?: {
    get(key: string): Promise<string | null>;
    set(key: string, value: string): Promise<void>;
    remove(key: string): Promise<void>;
  };
}
/**
 * Registry client
 */
declare class RegistryClient {
  private baseUrl;
  private channel;
  private publicKeys;
  private cacheTtl;
  private staleTtl;
  private enableCache;
  private fetchFn;
  private fetchTimeout;
  private storage?;
  private memoryCache;
  private currentStatus;
  constructor(options?: RegistryClientOptions);
  /**
   * Get registry URL for channel
   */
  private getRegistryUrl;
  /**
   * Get signature URL for channel
   */
  private getSignatureUrl;
  /**
   * Import public key from base64
   */
  private importPublicKey;
  /**
   * Verify signature
   */
  private verifySignature;
  /**
   * Verify registry signature
   */
  private verifyRegistrySignature;
  /**
   * Fetch registry and signature from network
   */
  private fetchFromNetwork;
  /**
   * Get registry with SWR pattern
   * - Returns cached immediately if available
   * - Refreshes in background
   */
  getRegistry(): Promise<WalletRegistryV1>;
  /**
   * Refresh registry from network
   */
  private refreshRegistry;
  /**
   * Update registry status
   */
  private updateStatus;
  /**
   * Get current registry status
   */
  getStatus(): RegistryStatus | null;
  /**
   * Save to persistent storage
   */
  private saveToStorage;
  /**
   * Load from persistent storage
   */
  private loadFromStorage;
  /**
   * Get all wallets
   */
  getWallets(): Promise<WalletInfo[]>;
  /**
   * Get wallet by ID
   */
  getWallet(walletId: string): Promise<WalletInfo>;
  /**
   * Get wallet entry (includes adapter config)
   */
  getWalletEntry(walletId: string): Promise<RegistryWalletEntry>;
  /**
   * Clear cache
   */
  clearCache(): void;
  /**
   * Check if cache is valid
   */
  isCacheValid(): boolean;
}

export {
  type CachedRegistry,
  type LastFetchAttempt,
  REGISTRY_SCHEMA_VERSION,
  type RegistryChannel,
  RegistryClient,
  type RegistryClientOptions,
  type RegistryMetadata,
  type RegistrySignature,
  type RegistryStatus,
  type RegistryWalletEntry,
  type WalletRegistryV1,
  registryEntryToMetadata,
  registryEntryToWalletInfo,
  validateRegistry,
  validateWalletEntry,
};
