// API SURFACE SNAPSHOT — @partylayer/react
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class NativeCIP0103Adapter implements WalletAdapter { readonly walletId: WalletId; readonly name: string; private provider; constructor(id: string, name: string, provider: CIP0103Provider); getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(_ctx: AdapterContext, _opts?: { timeoutMs?: number; partyId?: PartyId; }): Promise<AdapterConnectResult>; disconnect(_ctx: AdapterContext, _session: Session): Promise<void>; signMessage(_ctx: AdapterContext, _session: Session, params: SignMessageParams): Promise<SignedMessage>; signTransaction(_ctx: AdapterContext, _session: Session, params: SignTransactionParams): Promise<SignedTransaction>; submitTransaction(_ctx: AdapterContext, _session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; }
declare const darkTheme: PartyLayerTheme;
declare const lightTheme: PartyLayerTheme;
declare function ConnectButton({ label, connectedLabel, formatAddress, className, style, showDisconnect, }: ConnectButtonProps): react_jsx_runtime.JSX.Element;
declare function PartyLayerKit({ network, appName, children, registryUrl, channel, adapters, theme, walletIcons, walletOrder, sessionOptions, }: PartyLayerKitProps): react_jsx_runtime.JSX.Element;
declare function PartyLayerProvider({ client, children, sessionOptions, }: PartyLayerProviderProps): react_jsx_runtime.JSX.Element;
declare function ThemeProvider({ theme, children }: ThemeProviderProps): react_jsx_runtime.JSX.Element;
declare function WalletModal({ isOpen, onClose, onConnect, walletIcons: propIcons, walletOrder: propWalletOrder, }: WalletModalProps): react_jsx_runtime.JSX.Element | null;
declare function createLocalStorage(): SessionStorage;
declare function createNativeAdapter(discovered: DiscoveredProvider): NativeCIP0103Adapter;
declare function createSyntheticWalletInfo(discovered: EnrichedProvider, network: string): WalletInfo;
declare function resolveWalletIcon(walletId: string, walletIcons: WalletIconMap, registryIconUrl?: string): string | null;
declare function truncatePartyId(id: string, chars?: number): string;
declare function useAccount(): UseAccountReturn;
declare function useAccountEffect(parameters?: UseAccountEffectParameters): void;
declare function useClientSession(): Session | null;
declare function useConnect(): { connect: (options?: ConnectOptions) => Promise<Session | null>; isConnecting: boolean; error: Error | null; reset: () => void; };
declare function useDisconnect(): { disconnect: () => Promise<void>; isDisconnecting: boolean; error: Error | null; };
declare function useLedgerApi(): { ledgerApi: (params: LedgerApiParams) => Promise<LedgerApiResult | null>; isLoading: boolean; error: Error | null; };
declare function usePartyLayer(): _partylayer_sdk.CantonConnectClient;
declare function usePartyLayerContext(): PartyLayerContextValue;
declare function useRegistryStatus(): { status: RegistryStatus | null; refresh: () => Promise<void>; };
declare function useSession(): UseSessionReturn;
declare function useSignMessage(): { signMessage: (params: SignMessageParams) => Promise<SignedMessage | null>; isSigning: boolean; error: Error | null; };
declare function useSignTransaction(): { signTransaction: (params: SignTransactionParams) => Promise<SignedTransaction | null>; isSigning: boolean; error: Error | null; };
declare function useSubmitTransaction(): { submitTransaction: (params: SubmitTransactionParams) => Promise<TxReceipt | null>; isSubmitting: boolean; error: Error | null; };
declare function useTheme(): PartyLayerTheme;
declare function useWalletIcons(): WalletIconMap;
declare function useWallets(): { wallets: _partylayer_core.WalletInfo[]; isLoading: boolean; error: Error | null; };
export { PartyLayerProvider as CantonConnectProvider, ConnectButton, type ConnectButtonProps, NativeCIP0103Adapter, PartyLayerKit, type PartyLayerKitProps, PartyLayerProvider, type PartyLayerTheme, type SessionChain, ThemeProvider, type UseAccountEffectParameters, type UseAccountReturn, type UseSessionReturn, type WalletIconMap, WalletModal, type WalletModalProps, createLocalStorage, createNativeAdapter, createSyntheticWalletInfo, darkTheme, lightTheme, resolveWalletIcon, truncatePartyId, useAccount, useAccountEffect, usePartyLayer as useCantonConnect, useClientSession, useConnect, useDisconnect, useLedgerApi, usePartyLayer, usePartyLayerContext, useRegistryStatus, useSession, useSignMessage, useSignTransaction, useSubmitTransaction, useTheme, useWalletIcons, useWallets };
export { RegistryStatus } from '@partylayer/registry-client';
import * as _partylayer_core from '@partylayer/core';
import * as _partylayer_sdk from '@partylayer/sdk';
import * as react_jsx_runtime from 'react/jsx-runtime';
import { PartyLayerClient, Session, WalletInfo, ConnectOptions, LedgerApiParams, LedgerApiResult, RegistryStatus, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, WalletAdapter, AdapterClass, OfficialProviderAdapter, WalletId, CIP0103Provider, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, DiscoveredProvider, Cip0103StatusForDetection } from '@partylayer/sdk';
import { SessionStoreOptions, SessionStore, SessionAccount, SessionStatus, SessionState, SessionEvent, SessionStorage } from '@partylayer/session';
interface ConnectButtonProps { label?: string; connectedLabel?: 'address' | 'wallet' | 'custom'; formatAddress?: (partyId: string) => string; className?: string; style?: React.CSSProperties; showDisconnect?: boolean; }
interface EnrichedProvider extends DiscoveredProvider { status?: Cip0103StatusForDetection; matchedWallet?: WalletInfo; }
interface PartyLayerContextValue { client: PartyLayerClient | null; session: Session | null; wallets: WalletInfo[]; isLoading: boolean; error: Error | null; store: SessionStore | null; }
interface PartyLayerKitProps { network: 'devnet' | 'testnet' | 'mainnet'; appName: string; children: React.ReactNode; registryUrl?: string; channel?: 'stable' | 'beta'; adapters?: (WalletAdapter | AdapterClass | OfficialProviderAdapter)[]; theme?: 'light' | 'dark' | 'auto' | PartyLayerTheme; walletIcons?: WalletIconMap; walletOrder?: readonly string[]; sessionOptions?: Partial<SessionStoreOptions>; }
interface PartyLayerProviderProps { client: PartyLayerClient; children: React.ReactNode; network?: string; sessionOptions?: Partial<SessionStoreOptions>; }
interface PartyLayerTheme { mode: 'light' | 'dark'; colors: { primary: string; primaryHover: string; background: string; surface: string; text: string; textSecondary: string; border: string; success: string; successBg: string; error: string; errorBg: string; warning: string; warningBg: string; overlay: string; }; borderRadius: string; fontFamily: string; }
interface SessionChain { id: string; }
interface ThemeProviderProps { theme: 'light' | 'dark' | 'auto' | PartyLayerTheme; children: React.ReactNode; }
interface UseAccountEffectParameters { onConnect?: (data: { account: SessionAccount | null; accounts: readonly SessionAccount[]; networkId: string | null; }) => void; onDisconnect?: () => void; onPartyChanged?: (data: { previous: string | null; current: string | null; }) => void; }
interface UseAccountReturn { party: string | null; address: string | null; account: SessionAccount | null; accounts: readonly SessionAccount[]; status: SessionStatus; isConnected: boolean; isConnecting: boolean; isReconnecting: boolean; isDisconnected: boolean; networkId: string | null; chain: SessionChain | null; lastError: Error | null; }
interface UseSessionReturn extends SessionState { isConnected: boolean; isConnecting: boolean; isReconnecting: boolean; isDisconnected: boolean; connect(params?: Record<string, unknown>): Promise<SessionState>; disconnect(): Promise<void>; restore(): Promise<SessionState>; on<T extends SessionEvent['type']>(event: T, handler: (event: Extract<SessionEvent, { type: T; }>) => void): () => void; }
interface WalletModalProps { isOpen: boolean; onClose: () => void; onConnect?: (sessionId: string) => void; walletIcons?: WalletIconMap; walletOrder?: readonly string[]; }
type WalletIconMap = Record<string, string>;
