// API SURFACE SNAPSHOT — @partylayer/adapter-send
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class SendAdapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Send"; private readonly provider; constructor(options?: { detection?: ProviderDetection; provider?: SendProvider; }); getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, _opts?: { timeoutMs?: number; partyId?: PartyId; preferInstalled?: boolean; }): Promise<AdapterConnectResult>; disconnect(ctx: AdapterContext, _session: Session): Promise<void>; restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>; signMessage(ctx: AdapterContext, session: Session, params: SignMessageParams): Promise<SignedMessage>; signTransaction(_ctx: AdapterContext, _session: Session, _params: SignTransactionParams): Promise<SignedTransaction>; submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>; on(event: AdapterEventName, handler: (payload: unknown) => void): () => void; }
declare class SendAuthTimeoutError extends WalletNotInstalledError { constructor(originalMessage?: string); }
declare class SendKernelMismatchError extends WalletNotInstalledError { constructor(actualKernelId: string); }
declare class SendNotInstalledError extends WalletNotInstalledError { constructor(reason?: string); }
declare class SendProvider { private readonly detection; private readonly announceTimeoutMs; private readonly detectTimeoutMs; private readonly waitForProvider; private readonly injectedProvider?; private cachedChannel; private channelPromise; private channelPromiseTimeoutMs; private cachedStatus; constructor(detection?: ProviderDetection, options?: SendProviderOptions); private acceptedIds; private resolveChannel; private doResolveChannel; private channelRequest; isInstalled(): Promise<boolean>; isPotentiallyAvailable(): boolean; getKernelId(): Promise<string>; getStatus(): Promise<SendStatusResponse>; resetKernelCache(): void; resetStatusCache(): void; private fetchStatus; status(): Promise<SendStatusResponse>; connect(): Promise<SendStatusResponse>; disconnect(): Promise<null>; isConnected(): Promise<SendStatusResponse>; getActiveNetwork(): Promise<SendNetwork>; listAccounts(): Promise<SendAccount[]>; getPrimaryAccount(): Promise<SendAccount>; signMessage(message: string): Promise<{ signature: string; }>; prepareExecute(params: SendPrepareSubmissionRequest): Promise<null>; prepareExecuteAndWait(params: SendPrepareSubmissionRequest): Promise<SendPrepareExecuteAndWaitResult>; ledgerApi(req: SendLedgerApiRequest): Promise<SendLedgerApiResult>; on(event: SendEventName, listener: SendEventListener): void; off(event: SendEventName, listener: SendEventListener): void; }
declare const SEND_DOCS_URL = "https://sigilry.org";
declare const SEND_HOMEPAGE = "https://cantonwallet.com";
declare const SEND_INSTALL_URL = "https://sigilry.org";
declare const SEND_KERNEL_ID = "ldmohiccoioolenadmogclhoklmanpgi";
declare const SEND_SIGNING_METHOD: "webauthn-prf";
declare const SEND_SUPPORTED_NETWORKS: readonly [ "canton:mainnet" ];
declare const SendRpcErrorCode: { readonly PARSE_ERROR: -32700; readonly INVALID_REQUEST: -32600; readonly METHOD_NOT_FOUND: -32601; readonly INVALID_PARAMS: -32602; readonly INTERNAL_ERROR: -32603; readonly USER_REJECTED: 4001; readonly UNAUTHORIZED: 4100; readonly UNSUPPORTED_METHOD: 4200; readonly DISCONNECTED: 4900; readonly CHAIN_DISCONNECTED: 4901; readonly INVALID_INPUT: -32000; readonly RESOURCE_NOT_FOUND: -32001; readonly RESOURCE_UNAVAILABLE: -32002; readonly TRANSACTION_REJECTED: -32003; readonly METHOD_NOT_SUPPORTED: -32004; readonly LIMIT_EXCEEDED: -32005; };
declare function detectSendAuthTimeout(err: unknown): boolean;
declare function mapSigilryError(err: unknown, context: ErrorMappingContext): PartyLayerError;
declare function safePreview(value: unknown, maxLen?: number): string;
declare function templateIdHint(payload: unknown): string;
export { SEND_DOCS_URL, SEND_HOMEPAGE, SEND_INSTALL_URL, SEND_KERNEL_ID, SEND_SIGNING_METHOD, SEND_SUPPORTED_NETWORKS, type SendAccount, SendAdapter, SendAuthTimeoutError, type SendCantonProvider, type SendDisclosedContract, type SendEventListener, type SendEventName, type SendKernelInfo, SendKernelMismatchError, type SendLedgerApiRequest, type SendLedgerApiResult, type SendNetwork, SendNotInstalledError, type SendPrepareExecuteAndWaitResult, type SendPrepareSubmissionRequest, SendProvider, SendRpcErrorCode, type SendRpcMethod, type SendRpcRequest, type SendRpcResult, type SendRpcSchemas, type SendSignMessageRequest, type SendSignMessageResult, type SendStatusResponse, type SendTxChangedEvent, type SendTxExecutedEvent, detectSendAuthTimeout, mapSigilryError, safePreview, templateIdHint };
import * as _partylayer_core from '@partylayer/core';
import { DiscoveredProvider, WaitForAnnouncedOptions, AnnounceDiscoveryOptions } from '@partylayer/provider';
import { ProviderDetection, CIP0103Provider, WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult, AdapterEventName, WalletNotInstalledError, ErrorMappingContext, PartyLayerError } from '@partylayer/core';
interface SendAccount { primary: boolean; partyId: string; status: 'allocated' | 'initialized' | string; hint: string; publicKey: string; namespace: string; networkId: string; signingProviderId: string; externalTxId?: string; topologyTransactions?: string; disabled?: boolean; reason?: string; }
interface SendCantonProvider { request<M extends SendRpcMethod>(args: SendRpcRequest<M>): Promise<SendRpcResult<M>>; on(event: SendEventName, listener: SendEventListener): unknown; off?(event: SendEventName, listener: SendEventListener): unknown; removeListener?(event: SendEventName, listener: SendEventListener): unknown; }
interface SendDisclosedContract { templateId?: string; contractId?: string; createdEventBlob: string; synchronizerId?: string; }
interface SendKernelInfo { id: string; clientType: 'browser' | 'desktop' | 'mobile' | 'remote'; url?: string; userUrl?: string; }
interface SendLedgerApiRequest { requestMethod: 'get' | 'post' | 'patch' | 'put' | 'delete'; resource: string; body?: Record<string, unknown>; headers?: Record<string, string>; query?: Record<string, unknown>; path?: Record<string, string>; }
interface SendLedgerApiResult { response: string; }
interface SendNetwork { networkId: string; ledgerApi?: { baseUrl: string; }; }
interface SendPrepareExecuteAndWaitResult { tx: SendTxExecutedEvent; }
interface SendPrepareSubmissionRequest { commandId?: string; commands: SendCommand[]; actAs?: string[]; readAs?: string[]; disclosedContracts?: SendDisclosedContract[]; synchronizerId?: string; packageIdSelectionPreference?: string[]; }
interface SendProviderOptions { provider?: CIP0103Provider; announceTimeoutMs?: number; detectTimeoutMs?: number; waitForProvider?: (predicate: (p: DiscoveredProvider) => boolean, options?: WaitForAnnouncedOptions) => Promise<DiscoveredProvider | null>; discover?: (options?: AnnounceDiscoveryOptions) => Promise<DiscoveredProvider[]>; }
interface SendRpcSchemas { status: { params: void; result: SendStatusResponse; }; connect: { params: void; result: SendStatusResponse; }; disconnect: { params: void; result: null; }; isConnected: { params: void; result: SendStatusResponse; }; getActiveNetwork: { params: void; result: SendNetwork; }; getPrimaryAccount: { params: void; result: SendAccount; }; listAccounts: { params: void; result: SendAccount[]; }; prepareExecute: { params: SendPrepareSubmissionRequest; result: null; }; prepareExecuteAndWait: { params: SendPrepareSubmissionRequest; result: SendPrepareExecuteAndWaitResult; }; signMessage: { params: SendSignMessageRequest; result: SendSignMessageResult; }; ledgerApi: { params: SendLedgerApiRequest; result: SendLedgerApiResult; }; }
interface SendSignMessageRequest { message: string; }
interface SendSignMessageResult { signature: string; }
interface SendStatusResponse { kernel: SendKernelInfo; isConnected: boolean; isNetworkConnected: boolean; networkReason?: string; network?: SendNetwork; session?: { accessToken: string; userId: string; }; }
interface SendTxExecutedEvent { status: 'executed'; commandId: string; payload: { updateId: string; completionOffset: number; }; }
interface Window { canton?: SendCantonProvider; }
type SendCommand = { CreateCommand: Record<string, unknown>; } | { ExerciseCommand: Record<string, unknown>; } | { CreateAndExerciseCommand: Record<string, unknown>; } | { ExerciseByKeyCommand: Record<string, unknown>; };
type SendEventListener = (...args: unknown[]) => void;
type SendEventName = 'accountsChanged' | 'txChanged';
type SendRpcMethod = 'status' | 'connect' | 'disconnect' | 'isConnected' | 'getActiveNetwork' | 'getPrimaryAccount' | 'listAccounts' | 'prepareExecute' | 'prepareExecuteAndWait' | 'signMessage' | 'ledgerApi';
type SendRpcRequest<M extends SendRpcMethod> = SendRpcSchemas[M]['params'] extends void ? { method: M; params?: undefined; } : { method: M; params: SendRpcSchemas[M]['params']; };
type SendRpcResult<M extends SendRpcMethod> = SendRpcSchemas[M]['result'];
type SendTxChangedEvent = { status: 'pending'; commandId: string; } | { status: 'signed'; commandId: string; payload: { signature: string; signedBy: string; party: string; }; } | SendTxExecutedEvent | { status: 'failed'; commandId: string; };
