// API SURFACE SNAPSHOT — @partylayer/session
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import { CIP0103Account, CIP0103Provider } from '@partylayer/core';

/**
 * Pluggable persistence for the session store.
 *
 * The core never hardcodes `localStorage` — the runtime may be non-browser
 * (Node, RN, service worker). The framework layer injects a concrete storage;
 * if none is provided the store uses an in-memory default so it always works
 * and tests stay deterministic.
 */
type MaybePromise<T> = T | Promise<T>;
/**
 * Minimal async-friendly key/value storage. A browser app can adapt
 * `window.localStorage` (its methods are synchronous, which satisfies the
 * `MaybePromise` return types); a server can inject any KV implementation.
 */
interface SessionStorage {
  getItem(key: string): MaybePromise<string | null>;
  setItem(key: string, value: string): MaybePromise<void>;
  removeItem(key: string): MaybePromise<void>;
}
/** Default in-memory storage — safe in any runtime, never touches the DOM. */
declare function createMemoryStorage(): SessionStorage;

/**
 * Reconnect retry policy + backoff math (grant Milestone 1, S2).
 *
 * Pure + deterministic (jitter is opt-in and injectable) so the backoff SCHEDULE
 * can be asserted at exact fake-timer offsets in tests.
 */
/** Exponential-backoff reconnect policy. */
interface RetryPolicy {
  /** Delay before the FIRST retry (attempt 1), in ms. */
  baseDelayMs: number;
  /** Multiplier applied per attempt (`base * factor^(attempt-1)`). */
  factor: number;
  /** Upper bound on any single delay, in ms. */
  maxDelayMs: number;
  /** Max reconnect attempts before giving up. */
  maxAttempts: number;
  /** When true, randomize each delay within [50%, 100%] of the computed value. */
  jitter?: boolean;
}
/** Sane defaults: 0.5s → 1s → 2s → 4s → 8s, capped at 30s, 5 attempts, no jitter. */
declare const DEFAULT_RETRY_POLICY: RetryPolicy;
/**
 * Compute the delay (ms) before a 1-based `attempt`. Exponential, capped at
 * `maxDelayMs`. With `jitter`, scales by a `rand()` value in [0,1) into the
 * [50%,100%] band (`rand` injectable for determinism; defaults to Math.random).
 */
declare function computeBackoffDelay(
  policy: RetryPolicy,
  attempt: number,
  rand?: () => number
): number;

/** Minimal structural subset of BroadcastChannel we depend on. */
interface BroadcastChannelLike {
  postMessage(data: unknown): void;
  close(): void;
  onmessage: ((ev: { data: unknown }) => void) | null;
}
/** Factory for a channel; return `null` when broadcasting is unavailable. */
type ChannelFactory = (name: string) => BroadcastChannelLike | null;
/** Multi-tab options. `channelFactory` defaults to the global BroadcastChannel. */
interface BroadcastOptions {
  /** Override the channel factory (tests inject an in-memory hub). */
  channelFactory?: ChannelFactory;
}
/** Versioned cross-tab message. `kind` selects how a receiver applies it. */
interface BroadcastEnvelope {
  readonly v: 1;
  readonly kind: 'disconnect' | 'party' | 'network';
  readonly partyId?: string | null;
  readonly networkId?: string | null;
}
/** Default factory: the global BroadcastChannel, or `null` (SSR/Node-without-BC). */
declare const defaultChannelFactory: ChannelFactory;
/** A live multi-tab sync channel (or a no-op when unavailable). */
interface SyncChannel {
  /** True when a real channel is backing this (false ⇒ graceful no-op). */
  readonly active: boolean;
  /** Broadcast to OTHER tabs (never echoes to this sender). */
  post(env: BroadcastEnvelope): void;
  /** Register the receive handler (one per channel). */
  onMessage(handler: (env: BroadcastEnvelope) => void): void;
  /** Close + detach. */
  close(): void;
}
/**
 * Open an origin-bound, key-scoped sync channel. Name = the S1 `originTag`
 * pattern + the store's storage key, so two tabs of the SAME origin+session
 * share one channel and different origins never cross.
 */
declare function openSyncChannel(
  storageKey: string,
  options?: BroadcastOptions,
  explicitOrigin?: string
): SyncChannel;

/**
 * Public types for the framework-agnostic session core.
 */

/**
 * Connection status state machine.
 *
 * Derived from what the CIP-0103 provider actually exposes (a boolean
 * `connection.isConnected` on `statusChanged`, plus the `connected` event)
 * combined with the in-flight state of the store's own async operations:
 *
 *   disconnected ──connect()──▶ connecting ──success / statusChanged(true)──▶ connected
 *        ▲                          │                                            │
 *        │                          └────── error / rejection ──────────────────┤
 *        │                                                                       │
 *        ├───────────── disconnect() / statusChanged(false) ────────────────────┘
 *        │
 *        └──restore()/init()──▶ reconnecting ──active session──▶ connected
 *                                     └────── none ──▶ disconnected
 */
type SessionStatus = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';
/**
 * An account/party tracked by the session. This is the CIP-0103 account shape
 * verbatim — the core does not invent its own account model.
 */
type SessionAccount = CIP0103Account;
/**
 * Immutable snapshot of session state. `getSnapshot()` returns a STABLE
 * reference between notifications (only swapped when something actually
 * changed) so it is safe to feed directly into React's `useSyncExternalStore`
 * in Step 6b without tearing or render loops.
 */
interface SessionState {
  /** Connection status state-machine value. */
  readonly status: SessionStatus;
  /** Active (primary) account/party, or null when not connected. */
  readonly account: SessionAccount | null;
  /** All accounts the wallet exposed (active included). */
  readonly accounts: readonly SessionAccount[];
  /**
   * Active network in CAIP-2 form, or null. Today this is derived from
   * `statusChanged.network` / `getActiveNetwork()` because the WC adapter does
   * not emit `chainChanged` yet (see store wiring). Modeled forward-compatibly
   * so a future `chainChanged` event can feed the same field.
   */
  readonly networkId: string | null;
  /** Last error from a connect/restore/disconnect attempt, or null. */
  readonly lastError: Error | null;
}
interface SessionStoreOptions {
  /**
   * Pluggable persistence. Defaults to in-memory storage (no DOM access).
   * Inject a `localStorage`-backed adapter from the browser framework layer.
   */
  storage?: SessionStorage;
  /** Storage key used for the auto-reconnect marker. */
  storageKey?: string;
  /**
   * M1-S2: automatic reconnect with exponential backoff on TRANSIENT disconnects
   * (a `statusChanged(isConnected:false)` that was NOT an explicit
   * `store.disconnect()`). A `RetryPolicy` enables it; `false` disables it;
   * omitted ⇒ the default policy (enabled). NEVER fires after a user disconnect.
   */
  reconnect?: RetryPolicy | false;
  /**
   * M1-S2: runtime session-expiry → graceful re-auth. When `ttlMs` is set, an
   * active session arms a timer; on expiry the store emits `session:expired` and
   * invokes `onReauthRequired`. New operations submitted through
   * {@link SessionStore.enqueue} during re-auth are held in a bounded queue
   * (`pendingQueueSize`, default 32), resumed on success or rejected on
   * failure/overflow.
   */
  expiry?: ExpiryOptions;
  /**
   * M1-S3: multi-tab sync via BroadcastChannel. `true` enables it with the
   * default (global) channel; an object customizes the channel factory (tests
   * inject an in-memory hub). Omitted/`false` ⇒ disabled (single-tab). Graceful
   * no-op when BroadcastChannel is unavailable (SSR / Node). Origin-bound.
   */
  broadcast?: boolean | BroadcastOptions;
  /**
   * M1-S3: persist the FULL session snapshot (S1 envelope) at `storageKey`,
   * rewriting it on party/network change, instead of the legacy `'1'` marker.
   * Default `false` (legacy marker behavior preserved — additive).
   */
  persistSnapshot?: boolean;
  /**
   * M1-S3: invalidation hook called on a party-switch or network change — the
   * point where consumer cache invalidation (React-Query) wires in at S4/S6.
   * The session layer only emits + invalidates here.
   */
  onInvalidate?: (event: InvalidationEvent) => void | Promise<void>;
}
/** M1-S3 invalidation payload (party-switch or network change). */
interface InvalidationEvent {
  readonly type: 'party:changed' | 'network:changed';
  readonly previous: string | null;
  readonly current: string | null;
}
/** M1-S2 expiry / graceful re-auth configuration. */
interface ExpiryOptions {
  /** Time-to-live (ms from connect/restore) after which the session expires at runtime. */
  ttlMs?: number;
  /**
   * App-supplied re-auth hook invoked on runtime expiry. Perform a fresh connect
   * here; resolve to resume queued operations, reject to drain-reject them.
   */
  onReauthRequired?: (ctx: ReauthContext) => Promise<void> | void;
  /** Max operations held in the pending queue during re-auth. Default 32. */
  pendingQueueSize?: number;
}
/** Context passed to {@link ExpiryOptions.onReauthRequired}. */
interface ReauthContext {
  readonly reason: 'expired';
  /** Epoch-ms at which expiry fired. */
  readonly expiredAt: number;
}
/**
 * Structured resilience events (M1-S2). Subscribe via {@link SessionStore.on}.
 * `delayMs`/`attempt` let UIs surface backoff progress; `attempt` is 1-based.
 */
type SessionEvent =
  | {
      readonly type: 'reconnect:scheduled';
      readonly attempt: number;
      readonly delayMs: number;
    }
  | {
      readonly type: 'reconnect:attempt';
      readonly attempt: number;
    }
  | {
      readonly type: 'reconnect:succeeded';
      readonly attempt: number;
    }
  | {
      readonly type: 'reconnect:gaveup';
      readonly attempts: number;
      readonly lastError: Error | null;
    }
  | {
      readonly type: 'session:expired';
      readonly expiredAt: number;
    }
  | {
      readonly type: 'party:changed';
      readonly previous: string | null;
      readonly current: string | null;
    }
  | {
      readonly type: 'network:changed';
      readonly previous: string | null;
      readonly current: string | null;
    };
/**
 * Framework-agnostic session manager. Subscribable for `useSyncExternalStore`
 * (6b) and Vue composables; contains no React/Vue/DOM code.
 */
interface SessionStore {
  /** Current immutable snapshot (stable reference between changes). */
  getSnapshot(): SessionState;
  /** Subscribe to state changes. Returns an unsubscribe function. */
  subscribe(listener: () => void): () => void;
  /** Connect via the provider's CIP-0103 `connect` method. */
  connect(params?: Record<string, unknown>): Promise<SessionState>;
  /** Disconnect via the provider's CIP-0103 `disconnect` method. */
  disconnect(): Promise<void>;
  /**
   * Restore/initialize: rehydrate state from the live provider (`status` +
   * accounts) and the persisted auto-reconnect marker. The framework layer
   * (6b) calls this on mount; the dapp-sdk DiscoveryClient.create restore path
   * plugs in here.
   */
  restore(): Promise<SessionState>;
  /** Alias for `restore()`, named for the framework mount lifecycle. */
  init(): Promise<SessionState>;
  /** The underlying CIP-0103 provider. */
  getProvider(): CIP0103Provider;
  /**
   * M1-S2: subscribe to structured resilience events (reconnect lifecycle +
   * session expiry). Returns an unsubscribe function. Distinct from
   * {@link subscribe} (which is the state-change notifier for
   * `useSyncExternalStore`).
   */
  on(event: SessionEvent['type'], handler: (event: SessionEvent) => void): () => void;
  /**
   * M1-S2: run an operation, queuing it (bounded) if a re-auth is in progress —
   * resumed after re-auth succeeds, rejected on overflow or re-auth failure.
   * When no re-auth is in progress it runs immediately. Preserves QUEUED intent
   * + session context across re-auth; a tx already inside the wallet cannot be
   * resurrected (explicit limit — see README).
   */
  enqueue<T>(op: () => Promise<T>): Promise<T>;
  /** Tear down: remove all provider listeners and internal subscribers. */
  destroy(): void;
}

/**
 * Framework-agnostic session store over a CIP-0103 provider.
 *
 * Wraps any `CIP0103Provider` (the real `PartyLayerProvider`, the bridge, or
 * the `@partylayer/testing` mock) and tracks connection status + the active
 * account by subscribing to the SAME events the provider emits
 * (`statusChanged`, `accountsChanged`). Exposes a `subscribe`/`getSnapshot`
 * surface designed for React `useSyncExternalStore` (Step 6b) and Vue
 * composables — but contains no React/Vue/DOM code.
 */

declare function createSessionStore(
  provider: CIP0103Provider,
  options?: SessionStoreOptions
): SessionStore;

interface EncryptedStorageOptions {
  /**
   * Explicit origin tag for naming the key/data stores. Defaults to
   * `location.origin` (browser) or a stable off-origin literal (Node/tests).
   * Enables per-origin isolation + deterministic test naming.
   */
  origin?: string;
}
/** DEFAULT encrypted backend — ciphertext in IndexedDB, key in IndexedDB. */
declare function createEncryptedIndexedDBStorage(options?: EncryptedStorageOptions): SessionStorage;
/** Encrypted backend with ciphertext in localStorage — key STILL in IndexedDB. */
declare function createEncryptedLocalStorage(options?: EncryptedStorageOptions): SessionStorage;

/**
 * Versioned SESSION payload envelope + migration scaffold + restore/reconcile
 * helpers (grant Milestone 1, S1).
 *
 * This is the PLAINTEXT that the encrypted backends persist (compose:
 * `storage.setItem(key, encodeSessionEnvelope(snapshot))`). It carries an
 * explicit `version` so the session SCHEMA can evolve — `migrateSessionEnvelope`
 * is the switch-on-version scaffold that seeds the grant's "schema migration
 * helpers" acceptance item. (Distinct from the crypto-envelope format version
 * in crypto.ts, which governs the at-rest ciphertext shape.)
 *
 * Field names mirror the REAL session shape (`SessionState` in types.ts /
 * `CIP0103Account`): `account`, `accounts`, `networkId`, plus `connectedAt`
 * and an optional `expiresAt`.
 *
 * SAFETY: decode of a corrupt string or an unknown FUTURE schema version returns
 * `null` (never throws); `restoreSession` additionally CLEARS such an entry so a
 * forward-incompatible blob can't wedge the app.
 */

/** Current session-schema envelope version. Bump + extend `migrate` on shape changes. */
declare const CURRENT_SESSION_ENVELOPE_VERSION: 1;
/** The persisted session snapshot (schema v1). */
interface PersistedSessionSnapshot {
  /** Active (primary) account/party, or null. */
  readonly account: SessionAccount | null;
  /** All accounts the wallet exposed. */
  readonly accounts: readonly SessionAccount[];
  /** Active CAIP-2 network, or null. */
  readonly networkId: string | null;
  /** Epoch ms when this session was persisted/connected. */
  readonly connectedAt: number;
  /** Optional epoch-ms expiry; restore drops the snapshot once past it. */
  readonly expiresAt?: number;
}
/** Serialize a snapshot into the versioned envelope JSON string (the plaintext to encrypt). */
declare function encodeSessionEnvelope(snapshot: PersistedSessionSnapshot): string;
/**
 * Migration scaffold — switch on the envelope `version` and return a
 * current-shape snapshot, or `null` for an UNKNOWN (future / unsupported)
 * version. Add `case 2:` etc. here as the schema evolves; older versions map
 * forward into {@link PersistedSessionSnapshot}.
 */
declare function migrateSessionEnvelope(parsed: unknown): PersistedSessionSnapshot | null;
/** Decode an envelope plaintext into a snapshot, or `null` (corrupt / unknown version). Never throws. */
declare function decodeSessionEnvelope(plaintext: string): PersistedSessionSnapshot | null;
/**
 * Read + decode a persisted session from any {@link SessionStorage} (typically
 * an encrypted backend). Returns `null` and CLEARS the entry when the blob is
 * absent, corrupt, a wrong/unknown version, or expired — never throws.
 */
declare function restoreSession(
  storage: SessionStorage,
  key: string,
  now?: number
): Promise<PersistedSessionSnapshot | null>;
/** The live wallet status the restored snapshot is reconciled against. */
interface LiveSessionStatus {
  readonly account: SessionAccount | null;
  readonly networkId: string | null;
}
/** One field-level difference between the persisted snapshot and live status. */
interface SessionDiff {
  readonly field: 'account' | 'networkId';
  readonly persisted: string | null;
  readonly live: string | null;
}
/** Structured reconcile result — `matches` true iff there are no diffs. */
interface ReconcileResult {
  readonly matches: boolean;
  readonly diffs: readonly SessionDiff[];
}
/**
 * Compare an optimistic restored snapshot against the live wallet status and
 * emit a STRUCTURED diff (never throws). The framework layer uses this to decide
 * whether the optimistic snapshot can stand or must be reconciled/cleared
 * (e.g. user switched account/network in the wallet while away).
 */
declare function reconcileSession(
  snapshot: PersistedSessionSnapshot,
  live: LiveSessionStatus
): ReconcileResult;

export {
  type BroadcastChannelLike,
  type BroadcastEnvelope,
  type BroadcastOptions,
  CURRENT_SESSION_ENVELOPE_VERSION,
  type ChannelFactory,
  DEFAULT_RETRY_POLICY,
  type EncryptedStorageOptions,
  type ExpiryOptions,
  type InvalidationEvent,
  type LiveSessionStatus,
  type MaybePromise,
  type PersistedSessionSnapshot,
  type ReauthContext,
  type ReconcileResult,
  type RetryPolicy,
  type SessionAccount,
  type SessionDiff,
  type SessionEvent,
  type SessionState,
  type SessionStatus,
  type SessionStorage,
  type SessionStore,
  type SessionStoreOptions,
  type SyncChannel,
  computeBackoffDelay,
  createEncryptedIndexedDBStorage,
  createEncryptedLocalStorage,
  createMemoryStorage,
  createSessionStore,
  decodeSessionEnvelope,
  defaultChannelFactory,
  encodeSessionEnvelope,
  migrateSessionEnvelope,
  openSyncChannel,
  reconcileSession,
  restoreSession,
};
