// API SURFACE SNAPSHOT — @partylayer/react/query
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare const partyLayerKeys: { readonly all: readonly [ "partylayer" ]; readonly connect: () => readonly [ "partylayer", "connect" ]; readonly disconnect: () => readonly [ "partylayer", "disconnect" ]; readonly signMessage: () => readonly [ "partylayer", "signMessage" ]; readonly submitTransaction: () => readonly [ "partylayer", "submitTransaction" ]; readonly account: () => readonly [ "partylayer", "account" ]; readonly session: () => readonly [ "partylayer", "session" ]; readonly wallets: (params?: { filter?: unknown; }) => readonly [ "partylayer", "wallets", { filter?: unknown; } ]; readonly registryStatus: () => readonly [ "partylayer", "registryStatus" ]; };
declare function useConnect(parameters?: UseConnectParameters): UseConnectReturnType;
declare function useDisconnect(parameters?: UseDisconnectParameters): UseDisconnectReturnType;
declare function useSignMessage(parameters?: UseSignMessageParameters): UseSignMessageReturnType;
declare function useSubmitTransaction(parameters?: UseSubmitTransactionParameters): UseSubmitTransactionReturnType;
declare function useSuspenseWallets(parameters?: UseSuspenseWalletsParameters): UseSuspenseWalletsReturnType;
declare function useWallets(parameters?: UseWalletsParameters): UseWalletsReturnType;
export { type ConnectVariables, type DisconnectVariables, type PartyLayerKeys, type UseConnectParameters, type UseConnectReturnType, type UseDisconnectParameters, type UseDisconnectReturnType, type UseSignMessageParameters, type UseSignMessageReturnType, type UseSubmitTransactionParameters, type UseSubmitTransactionReturnType, type UseSuspenseWalletsParameters, type UseSuspenseWalletsReturnType, type UseWalletsParameters, type UseWalletsReturnType, partyLayerKeys, useConnect, useDisconnect, useSignMessage, useSubmitTransaction, useSuspenseWallets, useWallets };
import { ConnectOptions, Session, WalletFilter, WalletInfo, SignedMessage, SignMessageParams, TxReceipt, SubmitTransactionParams } from '@partylayer/sdk';
import { UseMutationOptions, UseMutationResult, UseQueryOptions, UseQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query';
interface UseConnectParameters { mutation?: Omit<UseMutationOptions<Session, Error, ConnectVariables>, 'mutationFn' | 'mutationKey'>; }
interface UseDisconnectParameters { mutation?: Omit<UseMutationOptions<void, Error, DisconnectVariables>, 'mutationFn' | 'mutationKey'>; }
interface UseSignMessageParameters { mutation?: Omit<UseMutationOptions<SignedMessage, Error, SignMessageParams>, 'mutationFn' | 'mutationKey'>; }
interface UseSubmitTransactionParameters { mutation?: Omit<UseMutationOptions<TxReceipt, Error, SubmitTransactionParams>, 'mutationFn' | 'mutationKey'>; }
interface UseSuspenseWalletsParameters { filter?: WalletFilter; query?: Omit<UseSuspenseQueryOptions<WalletInfo[], Error>, 'queryKey' | 'queryFn'>; }
interface UseWalletsParameters { filter?: WalletFilter; query?: Omit<UseQueryOptions<WalletInfo[], Error>, 'queryKey' | 'queryFn'>; }
type ConnectVariables = ConnectOptions | undefined;
type DisconnectVariables = void;
type PartyLayerKeys = typeof partyLayerKeys;
type UseConnectReturnType = UseMutationResult<Session, Error, ConnectVariables> & { connect: UseMutationResult<Session, Error, ConnectVariables>['mutate']; connectAsync: UseMutationResult<Session, Error, ConnectVariables>['mutateAsync']; };
type UseDisconnectReturnType = UseMutationResult<void, Error, DisconnectVariables> & { disconnect: UseMutationResult<void, Error, DisconnectVariables>['mutate']; disconnectAsync: UseMutationResult<void, Error, DisconnectVariables>['mutateAsync']; };
type UseSignMessageReturnType = UseMutationResult<SignedMessage, Error, SignMessageParams> & { signMessage: UseMutationResult<SignedMessage, Error, SignMessageParams>['mutate']; signMessageAsync: UseMutationResult<SignedMessage, Error, SignMessageParams>['mutateAsync']; };
type UseSubmitTransactionReturnType = UseMutationResult<TxReceipt, Error, SubmitTransactionParams> & { submitTransaction: UseMutationResult<TxReceipt, Error, SubmitTransactionParams>['mutate']; submitTransactionAsync: UseMutationResult<TxReceipt, Error, SubmitTransactionParams>['mutateAsync']; };
type UseSuspenseWalletsReturnType = UseSuspenseQueryResult<WalletInfo[], Error> & { wallets: UseSuspenseQueryResult<WalletInfo[], Error>['data']; };
type UseWalletsReturnType = UseQueryResult<WalletInfo[], Error> & { wallets: UseQueryResult<WalletInfo[], Error>['data']; };
