// API SURFACE SNAPSHOT — @partylayer/testing
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function createChannelHub(): ChannelHub;
declare function createSessionHarness(config?: SessionHarnessConfig): SessionHarness;
declare function createTransactionLifecycle(config?: LifecycleConfig): TransactionLifecycle;
declare function idbEntryCountScript(dbName: string): string;
declare function mockWalletInjectionScript(options?: MockWalletInjectionOptions): string;
declare function sessionDataDbName(origin: string): string;
declare function sessionKeyDbName(origin: string): string;
export { M as MOCK_SCENARIO_NAMES, a as MockMethod, b as MockScenario, c as MockScenarioName, d as MockWalletClient, e as MockWalletConfig, O as OfflineHarness, T as TxEventRecorder, f as connectMock, g as createMockWallet, h as createMockWalletClient, i as createOfflineHarness, r as recordTxEvents, s as scenarioToError } from './offline-CELeTEq9.js';
export { type ChannelHub, type LifecycleConfig, type LifecycleDelays, type LifecyclePhase, type MockWalletInjectionOptions, type SessionHarness, type SessionHarnessConfig, type TransactionLifecycle, createChannelHub, createSessionHarness, createTransactionLifecycle, idbEntryCountScript, mockWalletInjectionScript, sessionDataDbName, sessionKeyDbName };
import '@partylayer/provider';
import { CIP0103Provider, CIP0103TxChangedEvent } from '@partylayer/core';
import { ChannelFactory, SessionStore, SessionState, ExpiryOptions, RetryPolicy } from '@partylayer/session';
interface ChannelHub { factory: ChannelFactory; }
interface LifecycleConfig { commandId?: string; party?: string; signature?: string; updateId?: string; provider?: CIP0103Provider; delays?: LifecycleDelays; }
interface MockWalletInjectionOptions { walletId?: string; partyId?: string; networkId?: string; }
interface SessionHarness { readonly store: SessionStore; readonly provider: CIP0103Provider; connect(): Promise<SessionState>; dropConnection(): void; restoreConnection(): void; switchParty(partyId: string): void; expire(): Promise<void>; openTab(config?: Omit<SessionHarnessConfig, '_hub'>): SessionHarness; destroy(): void; }
interface SessionHarnessConfig { partyId?: string; networkId?: string; ttlMs?: number; onReauthRequired?: ExpiryOptions['onReauthRequired']; reconnect?: RetryPolicy | false; advanceTimers?: (ms: number) => void | Promise<void>; _hub?: ChannelHub; }
interface TransactionLifecycle { readonly commandId: string; readonly phase: LifecyclePhase; readonly isPreparing: boolean; readonly isSubmitting: boolean; readonly isConfirming: boolean; readonly isFinalized: boolean; readonly isFailed: boolean; on(event: string, listener: (event: CIP0103TxChangedEvent) => void): () => void; advance(): LifecyclePhase; fail(): void; start(): Promise<void>; reset(): void; }
type LifecycleDelays = Partial<Record<'preparing' | 'submitting' | 'confirming' | 'finalized', number>>;
type LifecyclePhase = 'idle' | 'preparing' | 'submitting' | 'confirming' | 'finalized' | 'failed';
